/*@ gen-okeys.h, generated by make-okey-map.pl.
 *@ See accmacvar.c for more */

static char const a_amv_var_names[] = {
   /* 0. [0]+15 --special-param, a_AMV_VF_RDONLY|a_AMV_VF_NODEL|a_AMV_VF_NOLOPTS */
   '-','-','s','p','e','c','i','a','l','-','p','a','r','a','m','\0',
   /* 1. [16]+1 ?, a_AMV_VF_RDONLY|a_AMV_VF_NODEL|a_AMV_VF_NOLOPTS */
   '?','\0',
   /* 2. [18]+1 !, a_AMV_VF_RDONLY|a_AMV_VF_NODEL|a_AMV_VF_NOLOPTS */
   '!','\0',
   /* 3. [20]+7 account, a_AMV_VF_RDONLY|a_AMV_VF_NODEL|a_AMV_VF_NOLOPTS */
   'a','c','c','o','u','n','t','\0',
   /* 4. [28]+19 add-file-recipients, a_AMV_VF_BOOL */
   'a','d','d','-','f','i','l','e','-','r','e','c','i','p','i','e','n','t','s','\0',
   /* 5. [48]+18 agent-shell-lookup, a_AMV_VF_OBSOLETE */
   'a','g','e','n','t','-','s','h','e','l','l','-','l','o','o','k','u','p','\0',
   /* 6. [67]+6 allnet, a_AMV_VF_BOOL */
   'a','l','l','n','e','t','\0',
   /* 7. [74]+6 append, a_AMV_VF_BOOL */
   'a','p','p','e','n','d','\0',
   /* 8. [81]+3 ask, a_AMV_VF_BOOL|a_AMV_VF_VIP */
   'a','s','k','\0',
   /* 9. [85]+8 askatend, a_AMV_VF_BOOL */
   'a','s','k','a','t','e','n','d','\0',
   /* 10. [94]+9 askattach, a_AMV_VF_BOOL */
   'a','s','k','a','t','t','a','c','h','\0',
   /* 11. [104]+6 askbcc, a_AMV_VF_BOOL */
   'a','s','k','b','c','c','\0',
   /* 12. [111]+5 askcc, a_AMV_VF_BOOL */
   'a','s','k','c','c','\0',
   /* 13. [117]+7 asksign, a_AMV_VF_BOOL */
   'a','s','k','s','i','g','n','\0',
   /* 14. [125]+7 asksend, a_AMV_VF_BOOL */
   'a','s','k','s','e','n','d','\0',
   /* 15. [133]+6 asksub, a_AMV_VF_BOOL|a_AMV_VF_I3VAL */
   'a','s','k','s','u','b','\0',
   /* 16. [140]+8 attrlist */
   'a','t','t','r','l','i','s','t','\0',
   /* 17. [149]+7 autobcc */
   'a','u','t','o','b','c','c','\0',
   /* 18. [157]+6 autocc */
   'a','u','t','o','c','c','\0',
   /* 19. [164]+12 autocollapse, a_AMV_VF_BOOL */
   'a','u','t','o','c','o','l','l','a','p','s','e','\0',
   /* 20. [177]+9 autoprint, a_AMV_VF_BOOL */
   'a','u','t','o','p','r','i','n','t','\0',
   /* 21. [187]+10 autothread, a_AMV_VF_BOOL|a_AMV_VF_OBSOLETE */
   'a','u','t','o','t','h','r','e','a','d','\0',
   /* 22. [198]+8 autosort */
   'a','u','t','o','s','o','r','t','\0',
   /* 23. [207]+4 bang, a_AMV_VF_BOOL */
   'b','a','n','g','\0',
   /* 24. [212]+12 bind-timeout, a_AMV_VF_VIP|a_AMV_VF_NOTEMPTY|a_AMV_VF_POSNUM|a_AMV_VF_OBSOLETE */
   'b','i','n','d','-','t','i','m','e','o','u','t','\0',
   /* 25. [225]+23 bind-inter-byte-timeout, a_AMV_VF_DEFVAL|a_AMV_VF_NOTEMPTY|a_AMV_VF_POSNUM */
   'b','i','n','d','-','i','n','t','e','r','-','b','y','t','e','-','t','i','m','e','o','u','t','\0',
   /* 26. [249]+22 bind-inter-key-timeout, a_AMV_VF_NOTEMPTY|a_AMV_VF_POSNUM */
   'b','i','n','d','-','i','n','t','e','r','-','k','e','y','-','t','i','m','e','o','u','t','\0',
   /* 27. [272]+11 bsdannounce, a_AMV_VF_BOOL|a_AMV_VF_OBSOLETE */
   'b','s','d','a','n','n','o','u','n','c','e','\0',
   /* 28. [284]+9 bsdcompat, a_AMV_VF_BOOL */
   'b','s','d','c','o','m','p','a','t','\0',
   /* 29. [294]+8 bsdflags, a_AMV_VF_BOOL */
   'b','s','d','f','l','a','g','s','\0',
   /* 30. [303]+11 bsdheadline, a_AMV_VF_BOOL */
   'b','s','d','h','e','a','d','l','i','n','e','\0',
   /* 31. [315]+7 bsdmsgs, a_AMV_VF_BOOL */
   'b','s','d','m','s','g','s','\0',
   /* 32. [323]+8 bsdorder, a_AMV_VF_BOOL */
   'b','s','d','o','r','d','e','r','\0',
   /* 33. [332]+8 build-cc, a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL */
   'b','u','i','l','d','-','c','c','\0',
   /* 34. [341]+8 build-ld, a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL */
   'b','u','i','l','d','-','l','d','\0',
   /* 35. [350]+8 build-os, a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL */
   'b','u','i','l','d','-','o','s','\0',
   /* 36. [359]+10 build-rest, a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL */
   'b','u','i','l','d','-','r','e','s','t','\0',
   /* 37. [370]+7 COLUMNS, a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY|a_AMV_VF_POSNUM */
   'C','O','L','U','M','N','S','\0',
   /* 38. [378]+12 charset-7bit, a_AMV_VF_VIP|a_AMV_VF_DEFVAL|a_AMV_VF_NOTEMPTY */
   'c','h','a','r','s','e','t','-','7','b','i','t','\0',
   /* 39. [391]+12 charset-8bit, a_AMV_VF_VIP|a_AMV_VF_DEFVAL|a_AMV_VF_NOTEMPTY */
   'c','h','a','r','s','e','t','-','8','b','i','t','\0',
   /* 40. [404]+20 charset-unknown-8bit, a_AMV_VF_VIP */
   'c','h','a','r','s','e','t','-','u','n','k','n','o','w','n','-','8','b','i','t','\0',
   /* 41. [425]+3 cmd */
   'c','m','d','\0',
   /* 42. [429]+14 colour-disable, a_AMV_VF_BOOL */
   'c','o','l','o','u','r','-','d','i','s','a','b','l','e','\0',
   /* 43. [444]+12 colour-pager, a_AMV_VF_BOOL|a_AMV_VF_OBSOLETE */
   'c','o','l','o','u','r','-','p','a','g','e','r','\0',
   /* 44. [457]+12 contact-mail, a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL */
   'c','o','n','t','a','c','t','-','m','a','i','l','\0',
   /* 45. [470]+11 contact-web, a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL */
   'c','o','n','t','a','c','t','-','w','e','b','\0',
   /* 46. [482]+37 content-description-forwarded-message, a_AMV_VF_DEFVAL */
   'c','o','n','t','e','n','t','-','d','e','s','c','r','i','p','t','i','o','n','-','f','o','r','w','a','r','d','e','d','-','m','e','s','s','a','g','e','\0',
   /* 47. [520]+36 content-description-quote-attachment, a_AMV_VF_DEFVAL */
   'c','o','n','t','e','n','t','-','d','e','s','c','r','i','p','t','i','o','n','-','q','u','o','t','e','-','a','t','t','a','c','h','m','e','n','t','\0',
   /* 48. [557]+33 content-description-smime-message, a_AMV_VF_DEFVAL */
   'c','o','n','t','e','n','t','-','d','e','s','c','r','i','p','t','i','o','n','-','s','m','i','m','e','-','m','e','s','s','a','g','e','\0',
   /* 49. [591]+35 content-description-smime-signature, a_AMV_VF_DEFVAL */
   'c','o','n','t','e','n','t','-','d','e','s','c','r','i','p','t','i','o','n','-','s','m','i','m','e','-','s','i','g','n','a','t','u','r','e','\0',
   /* 50. [627]+3 crt, a_AMV_VF_POSNUM */
   'c','r','t','\0',
   /* 51. [631]+9 customhdr, a_AMV_VF_VIP */
   'c','u','s','t','o','m','h','d','r','\0',
   /* 52. [641]+4 DEAD, a_AMV_VF_DEFVAL|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY */
   'D','E','A','D','\0',
   /* 53. [646]+9 datefield, a_AMV_VF_I3VAL */
   'd','a','t','e','f','i','e','l','d','\0',
   /* 54. [656]+23 datefield-markout-older, a_AMV_VF_I3VAL */
   'd','a','t','e','f','i','e','l','d','-','m','a','r','k','o','u','t','-','o','l','d','e','r','\0',
   /* 55. [680]+5 debug, a_AMV_VF_BOOL|a_AMV_VF_VIP */
   'd','e','b','u','g','\0',
   /* 56. [686]+29 disposition-notification-send, a_AMV_VF_BOOL */
   'd','i','s','p','o','s','i','t','i','o','n','-','n','o','t','i','f','i','c','a','t','i','o','n','-','s','e','n','d','\0',
   /* 57. [716]+3 dot, a_AMV_VF_BOOL */
   'd','o','t','\0',
   /* 58. [720]+15 dotlock-disable, a_AMV_VF_BOOL */
   'd','o','t','l','o','c','k','-','d','i','s','a','b','l','e','\0',
   /* 59. [736]+20 dotlock-ignore-error, a_AMV_VF_BOOL|a_AMV_VF_OBSOLETE */
   'd','o','t','l','o','c','k','-','i','g','n','o','r','e','-','e','r','r','o','r','\0',
   /* 60. [757]+6 EDITOR, a_AMV_VF_DEFVAL|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY */
   'E','D','I','T','O','R','\0',
   /* 61. [764]+9 editalong */
   'e','d','i','t','a','l','o','n','g','\0',
   /* 62. [774]+11 editheaders, a_AMV_VF_BOOL */
   'e','d','i','t','h','e','a','d','e','r','s','\0',
   /* 63. [786]+10 emptystart, a_AMV_VF_BOOL */
   'e','m','p','t','y','s','t','a','r','t','\0',
   /* 64. [797]+8 encoding, a_AMV_VF_OBSOLETE */
   'e','n','c','o','d','i','n','g','\0',
   /* 65. [806]+7 errexit, a_AMV_VF_BOOL */
   'e','r','r','e','x','i','t','\0',
   /* 66. [814]+12 errors-limit, a_AMV_VF_DEFVAL|a_AMV_VF_NOTEMPTY|a_AMV_VF_POSNUM */
   'e','r','r','o','r','s','-','l','i','m','i','t','\0',
   /* 67. [827]+6 escape, a_AMV_VF_DEFVAL */
   'e','s','c','a','p','e','\0',
   /* 68. [834]+10 expandaddr */
   'e','x','p','a','n','d','a','d','d','r','\0',
   /* 69. [845]+22 expandaddr-domaincheck, a_AMV_VF_NOTEMPTY */
   'e','x','p','a','n','d','a','d','d','r','-','d','o','m','a','i','n','c','h','e','c','k','\0',
   /* 70. [868]+10 expandargv */
   'e','x','p','a','n','d','a','r','g','v','\0',
   /* 71. [879]+8 features, a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL */
   'f','e','a','t','u','r','e','s','\0',
   /* 72. [888]+5 flipr, a_AMV_VF_BOOL */
   'f','l','i','p','r','\0',
   /* 73. [894]+6 folder, a_AMV_VF_VIP */
   'f','o','l','d','e','r','\0',
   /* 74. [901]+15 folder-resolved, a_AMV_VF_RDONLY|a_AMV_VF_NODEL */
   'f','o','l','d','e','r','-','r','e','s','o','l','v','e','d','\0',
   /* 75. [917]+11 folder-hook */
   'f','o','l','d','e','r','-','h','o','o','k','\0',
   /* 76. [929]+11 followup-to, a_AMV_VF_BOOL */
   'f','o','l','l','o','w','u','p','-','t','o','\0',
   /* 77. [941]+18 followup-to-add-cc, a_AMV_VF_BOOL */
   'f','o','l','l','o','w','u','p','-','t','o','-','a','d','d','-','c','c','\0',
   /* 78. [960]+18 followup-to-honour */
   'f','o','l','l','o','w','u','p','-','t','o','-','h','o','n','o','u','r','\0',
   /* 79. [979]+14 forward-add-cc, a_AMV_VF_BOOL */
   'f','o','r','w','a','r','d','-','a','d','d','-','c','c','\0',
   /* 80. [994]+21 forward-as-attachment, a_AMV_VF_BOOL */
   'f','o','r','w','a','r','d','-','a','s','-','a','t','t','a','c','h','m','e','n','t','\0',
   /* 81. [1016]+19 forward-inject-head */
   'f','o','r','w','a','r','d','-','i','n','j','e','c','t','-','h','e','a','d','\0',
   /* 82. [1036]+19 forward-inject-tail */
   'f','o','r','w','a','r','d','-','i','n','j','e','c','t','-','t','a','i','l','\0',
   /* 83. [1056]+4 from, a_AMV_VF_VIP */
   'f','r','o','m','\0',
   /* 84. [1061]+9 fullnames, a_AMV_VF_BOOL */
   'f','u','l','l','n','a','m','e','s','\0',
   /* 85. [1071]+10 fwdheading, a_AMV_VF_OBSOLETE */
   'f','w','d','h','e','a','d','i','n','g','\0',
   /* 86. [1082]+4 HOME, a_AMV_VF_VIP|a_AMV_VF_NODEL|a_AMV_VF_IMPORT|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY */
   'H','O','M','E','\0',
   /* 87. [1087]+6 header, a_AMV_VF_BOOL|a_AMV_VF_I3VAL */
   'h','e','a','d','e','r','\0',
   /* 88. [1094]+8 headline */
   'h','e','a','d','l','i','n','e','\0',
   /* 89. [1103]+13 headline-bidi */
   'h','e','a','d','l','i','n','e','-','b','i','d','i','\0',
   /* 90. [1117]+14 headline-plain, a_AMV_VF_BOOL */
   'h','e','a','d','l','i','n','e','-','p','l','a','i','n','\0',
   /* 91. [1132]+12 history-file */
   'h','i','s','t','o','r','y','-','f','i','l','e','\0',
   /* 92. [1145]+13 history-gabby */
   'h','i','s','t','o','r','y','-','g','a','b','b','y','\0',
   /* 93. [1159]+21 history-gabby-persist, a_AMV_VF_BOOL */
   'h','i','s','t','o','r','y','-','g','a','b','b','y','-','p','e','r','s','i','s','t','\0',
   /* 94. [1181]+12 history-size, a_AMV_VF_NOTEMPTY|a_AMV_VF_POSNUM */
   'h','i','s','t','o','r','y','-','s','i','z','e','\0',
   /* 95. [1194]+4 hold, a_AMV_VF_BOOL */
   'h','o','l','d','\0',
   /* 96. [1199]+8 hostname, a_AMV_VF_VIP */
   'h','o','s','t','n','a','m','e','\0',
   /* 97. [1208]+12 idna-disable, a_AMV_VF_BOOL */
   'i','d','n','a','-','d','i','s','a','b','l','e','\0',
   /* 98. [1221]+3 ifs, a_AMV_VF_VIP|a_AMV_VF_DEFVAL */
   'i','f','s','\0',
   /* 99. [1225]+6 ifs-ws, a_AMV_VF_VIP|a_AMV_VF_RDONLY|a_AMV_VF_NODEL|a_AMV_VF_I3VAL */
   'i','f','s','-','w','s','\0',
   /* 100. [1232]+6 ignore, a_AMV_VF_BOOL */
   'i','g','n','o','r','e','\0',
   /* 101. [1239]+9 ignoreeof, a_AMV_VF_BOOL */
   'i','g','n','o','r','e','e','o','f','\0',
   /* 102. [1249]+5 inbox */
   'i','n','b','o','x','\0',
   /* 103. [1255]+12 indentprefix, a_AMV_VF_DEFVAL */
   'i','n','d','e','n','t','p','r','e','f','i','x','\0',
   /* 104. [1268]+4 keep, a_AMV_VF_BOOL */
   'k','e','e','p','\0',
   /* 105. [1273]+19 keep-content-length, a_AMV_VF_BOOL */
   'k','e','e','p','-','c','o','n','t','e','n','t','-','l','e','n','g','t','h','\0',
   /* 106. [1293]+8 keepsave, a_AMV_VF_BOOL */
   'k','e','e','p','s','a','v','e','\0',
   /* 107. [1302]+4 LANG, a_AMV_VF_VIP|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY */
   'L','A','N','G','\0',
   /* 108. [1307]+6 LC_ALL, a_AMV_VF_VIP|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY */
   'L','C','_','A','L','L','\0',
   /* 109. [1314]+8 LC_CTYPE, a_AMV_VF_VIP|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY */
   'L','C','_','C','T','Y','P','E','\0',
   /* 110. [1323]+5 LINES, a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY|a_AMV_VF_POSNUM */
   'L','I','N','E','S','\0',
   /* 111. [1329]+6 LISTER, a_AMV_VF_DEFVAL|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY */
   'L','I','S','T','E','R','\0',
   /* 112. [1336]+7 LOGNAME, a_AMV_VF_RDONLY|a_AMV_VF_IMPORT|a_AMV_VF_ENV */
   'L','O','G','N','A','M','E','\0',
   /* 113. [1344]+18 line-editor-config, a_AMV_VF_NOTEMPTY */
   'l','i','n','e','-','e','d','i','t','o','r','-','c','o','n','f','i','g','\0',
   /* 114. [1363]+27 line-editor-cpl-word-breaks, a_AMV_VF_DEFVAL */
   'l','i','n','e','-','e','d','i','t','o','r','-','c','p','l','-','w','o','r','d','-','b','r','e','a','k','s','\0',
   /* 115. [1391]+19 line-editor-disable, a_AMV_VF_BOOL */
   'l','i','n','e','-','e','d','i','t','o','r','-','d','i','s','a','b','l','e','\0',
   /* 116. [1411]+23 line-editor-no-defaults, a_AMV_VF_BOOL */
   'l','i','n','e','-','e','d','i','t','o','r','-','n','o','-','d','e','f','a','u','l','t','s','\0',
   /* 117. [1435]+10 log-prefix, a_AMV_VF_NODEL|a_AMV_VF_I3VAL */
   'l','o','g','-','p','r','e','f','i','x','\0',
   /* 118. [1446]+4 MAIL, a_AMV_VF_ENV */
   'M','A','I','L','\0',
   /* 119. [1451]+8 MAILCAPS, a_AMV_VF_DEFVAL|a_AMV_VF_IMPORT|a_AMV_VF_ENV */
   'M','A','I','L','C','A','P','S','\0',
   /* 120. [1460]+6 MAILRC, a_AMV_VF_DEFVAL|a_AMV_VF_IMPORT|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY */
   'M','A','I','L','R','C','\0',
   /* 121. [1467]+18 MAILX_NO_SYSTEM_RC, a_AMV_VF_BOOL|a_AMV_VF_IMPORT|a_AMV_VF_ENV */
   'M','A','I','L','X','_','N','O','_','S','Y','S','T','E','M','_','R','C','\0',
   /* 122. [1486]+4 MBOX, a_AMV_VF_DEFVAL|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY */
   'M','B','O','X','\0',
   /* 123. [1491]+16 mailbox-basename, a_AMV_VF_RDONLY|a_AMV_VF_NODEL|a_AMV_VF_NOLOPTS */
   'm','a','i','l','b','o','x','-','b','a','s','e','n','a','m','e','\0',
   /* 124. [1508]+15 mailbox-display, a_AMV_VF_RDONLY|a_AMV_VF_NODEL|a_AMV_VF_NOLOPTS */
   'm','a','i','l','b','o','x','-','d','i','s','p','l','a','y','\0',
   /* 125. [1524]+16 mailbox-resolved, a_AMV_VF_RDONLY|a_AMV_VF_NODEL|a_AMV_VF_NOLOPTS */
   'm','a','i','l','b','o','x','-','r','e','s','o','l','v','e','d','\0',
   /* 126. [1541]+15 mailcap-disable, a_AMV_VF_BOOL */
   'm','a','i','l','c','a','p','-','d','i','s','a','b','l','e','\0',
   /* 127. [1557]+14 mailx-extra-rc, a_AMV_VF_NOTEMPTY */
   'm','a','i','l','x','-','e','x','t','r','a','-','r','c','\0',
   /* 128. [1572]+12 markanswered, a_AMV_VF_BOOL */
   'm','a','r','k','a','n','s','w','e','r','e','d','\0',
   /* 129. [1585]+16 mbox-fcc-and-pcc, a_AMV_VF_BOOL|a_AMV_VF_I3VAL */
   'm','b','o','x','-','f','c','c','-','a','n','d','-','p','c','c','\0',
   /* 130. [1602]+12 mbox-rfc4155, a_AMV_VF_BOOL */
   'm','b','o','x','-','r','f','c','4','1','5','5','\0',
   /* 131. [1615]+8 memdebug, a_AMV_VF_BOOL|a_AMV_VF_VIP */
   'm','e','m','d','e','b','u','g','\0',
   /* 132. [1624]+18 message-id-disable, a_AMV_VF_BOOL */
   'm','e','s','s','a','g','e','-','i','d','-','d','i','s','a','b','l','e','\0',
   /* 133. [1643]+19 message-inject-head */
   'm','e','s','s','a','g','e','-','i','n','j','e','c','t','-','h','e','a','d','\0',
   /* 134. [1663]+19 message-inject-tail */
   'm','e','s','s','a','g','e','-','i','n','j','e','c','t','-','t','a','i','l','\0',
   /* 135. [1683]+5 metoo, a_AMV_VF_BOOL */
   'm','e','t','o','o','\0',
   /* 136. [1689]+24 mime-allow-text-controls, a_AMV_VF_BOOL */
   'm','i','m','e','-','a','l','l','o','w','-','t','e','x','t','-','c','o','n','t','r','o','l','s','\0',
   /* 137. [1714]+28 mime-alternative-favour-rich, a_AMV_VF_BOOL */
   'm','i','m','e','-','a','l','t','e','r','n','a','t','i','v','e','-','f','a','v','o','u','r','-','r','i','c','h','\0',
   /* 138. [1743]+21 mime-counter-evidence, a_AMV_VF_POSNUM */
   'm','i','m','e','-','c','o','u','n','t','e','r','-','e','v','i','d','e','n','c','e','\0',
   /* 139. [1765]+13 mime-encoding */
   'm','i','m','e','-','e','n','c','o','d','i','n','g','\0',
   /* 140. [1779]+18 mime-force-sendout, a_AMV_VF_BOOL */
   'm','i','m','e','-','f','o','r','c','e','-','s','e','n','d','o','u','t','\0',
   /* 141. [1798]+22 mimetypes-load-control */
   'm','i','m','e','t','y','p','e','s','-','l','o','a','d','-','c','o','n','t','r','o','l','\0',
   /* 142. [1821]+3 mta, a_AMV_VF_DEFVAL|a_AMV_VF_NOTEMPTY */
   'm','t','a','\0',
   /* 143. [1825]+11 mta-aliases, a_AMV_VF_NOTEMPTY */
   'm','t','a','-','a','l','i','a','s','e','s','\0',
   /* 144. [1837]+13 mta-arguments */
   'm','t','a','-','a','r','g','u','m','e','n','t','s','\0',
   /* 145. [1851]+24 mta-no-default-arguments, a_AMV_VF_BOOL */
   'm','t','a','-','n','o','-','d','e','f','a','u','l','t','-','a','r','g','u','m','e','n','t','s','\0',
   /* 146. [1876]+25 mta-no-receiver-arguments, a_AMV_VF_BOOL */
   'm','t','a','-','n','o','-','r','e','c','e','i','v','e','r','-','a','r','g','u','m','e','n','t','s','\0',
   /* 147. [1902]+9 mta-argv0, a_AMV_VF_DEFVAL|a_AMV_VF_NOTEMPTY */
   'm','t','a','-','a','r','g','v','0','\0',
   /* 148. [1912]+10 mta-bcc-ok, a_AMV_VF_BOOL */
   'm','t','a','-','b','c','c','-','o','k','\0',
   /* 149. [1923]+13 NAIL_EXTRA_RC, a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY|a_AMV_VF_OBSOLETE */
   'N','A','I','L','_','E','X','T','R','A','_','R','C','\0',
   /* 150. [1937]+17 NAIL_NO_SYSTEM_RC, a_AMV_VF_BOOL|a_AMV_VF_IMPORT|a_AMV_VF_ENV|a_AMV_VF_OBSOLETE */
   'N','A','I','L','_','N','O','_','S','Y','S','T','E','M','_','R','C','\0',
   /* 151. [1955]+9 NAIL_HEAD, a_AMV_VF_OBSOLETE */
   'N','A','I','L','_','H','E','A','D','\0',
   /* 152. [1965]+13 NAIL_HISTFILE, a_AMV_VF_OBSOLETE */
   'N','A','I','L','_','H','I','S','T','F','I','L','E','\0',
   /* 153. [1979]+13 NAIL_HISTSIZE, a_AMV_VF_NOTEMPTY|a_AMV_VF_NUM|a_AMV_VF_OBSOLETE */
   'N','A','I','L','_','H','I','S','T','S','I','Z','E','\0',
   /* 154. [1993]+9 NAIL_TAIL, a_AMV_VF_OBSOLETE */
   'N','A','I','L','_','T','A','I','L','\0',
   /* 155. [2003]+5 NETRC, a_AMV_VF_DEFVAL|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY */
   'N','E','T','R','C','\0',
   /* 156. [2009]+12 netrc-lookup, a_AMV_VF_BOOL|a_AMV_VF_CHAIN */
   'n','e','t','r','c','-','l','o','o','k','u','p','\0',
   /* 157. [2022]+10 netrc-pipe */
   'n','e','t','r','c','-','p','i','p','e','\0',
   /* 158. [2033]+10 newfolders */
   'n','e','w','f','o','l','d','e','r','s','\0',
   /* 159. [2044]+7 newmail */
   'n','e','w','m','a','i','l','\0',
   /* 160. [2052]+18 on-account-cleanup, a_AMV_VF_NOTEMPTY */
   'o','n','-','a','c','c','o','u','n','t','-','c','l','e','a','n','u','p','\0',
   /* 161. [2071]+18 on-compose-cleanup, a_AMV_VF_NOTEMPTY */
   'o','n','-','c','o','m','p','o','s','e','-','c','l','e','a','n','u','p','\0',
   /* 162. [2090]+16 on-compose-enter, a_AMV_VF_NOTEMPTY */
   'o','n','-','c','o','m','p','o','s','e','-','e','n','t','e','r','\0',
   /* 163. [2107]+16 on-compose-leave, a_AMV_VF_NOTEMPTY */
   'o','n','-','c','o','m','p','o','s','e','-','l','e','a','v','e','\0',
   /* 164. [2124]+17 on-compose-splice, a_AMV_VF_NOTEMPTY */
   'o','n','-','c','o','m','p','o','s','e','-','s','p','l','i','c','e','\0',
   /* 165. [2142]+23 on-compose-splice-shell, a_AMV_VF_NOTEMPTY */
   'o','n','-','c','o','m','p','o','s','e','-','s','p','l','i','c','e','-','s','h','e','l','l','\0',
   /* 166. [2166]+19 on-history-addition, a_AMV_VF_NOTEMPTY */
   'o','n','-','h','i','s','t','o','r','y','-','a','d','d','i','t','i','o','n','\0',
   /* 167. [2186]+17 on-main-loop-tick, a_AMV_VF_NOTEMPTY */
   'o','n','-','m','a','i','n','-','l','o','o','p','-','t','i','c','k','\0',
   /* 168. [2204]+15 on-program-exit, a_AMV_VF_NOTEMPTY */
   'o','n','-','p','r','o','g','r','a','m','-','e','x','i','t','\0',
   /* 169. [2220]+17 on-resend-cleanup, a_AMV_VF_NOTEMPTY */
   'o','n','-','r','e','s','e','n','d','-','c','l','e','a','n','u','p','\0',
   /* 170. [2238]+15 on-resend-enter, a_AMV_VF_NOTEMPTY */
   'o','n','-','r','e','s','e','n','d','-','e','n','t','e','r','\0',
   /* 171. [2254]+9 outfolder, a_AMV_VF_BOOL */
   'o','u','t','f','o','l','d','e','r','\0',
   /* 172. [2264]+5 PAGER, a_AMV_VF_DEFVAL|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY */
   'P','A','G','E','R','\0',
   /* 173. [2270]+4 PATH, a_AMV_VF_NODEL|a_AMV_VF_IMPORT|a_AMV_VF_ENV */
   'P','A','T','H','\0',
   /* 174. [2275]+15 POSIXLY_CORRECT, a_AMV_VF_BOOL|a_AMV_VF_VIP|a_AMV_VF_IMPORT|a_AMV_VF_ENV */
   'P','O','S','I','X','L','Y','_','C','O','R','R','E','C','T','\0',
   /* 175. [2291]+4 page, a_AMV_VF_BOOL */
   'p','a','g','e','\0',
   /* 176. [2296]+8 password, a_AMV_VF_CHAIN */
   'p','a','s','s','w','o','r','d','\0',
   /* 177. [2305]+7 piperaw, a_AMV_VF_BOOL */
   'p','i','p','e','r','a','w','\0',
   /* 178. [2313]+9 pop3-auth, a_AMV_VF_CHAIN */
   'p','o','p','3','-','a','u','t','h','\0',
   /* 179. [2323]+14 pop3-bulk-load, a_AMV_VF_BOOL */
   'p','o','p','3','-','b','u','l','k','-','l','o','a','d','\0',
   /* 180. [2338]+14 pop3-keepalive, a_AMV_VF_NOTEMPTY|a_AMV_VF_POSNUM */
   'p','o','p','3','-','k','e','e','p','a','l','i','v','e','\0',
   /* 181. [2353]+12 pop3-no-apop, a_AMV_VF_BOOL|a_AMV_VF_CHAIN */
   'p','o','p','3','-','n','o','-','a','p','o','p','\0',
   /* 182. [2366]+17 pop3-use-starttls, a_AMV_VF_BOOL|a_AMV_VF_CHAIN */
   'p','o','p','3','-','u','s','e','-','s','t','a','r','t','t','l','s','\0',
   /* 183. [2384]+5 posix, a_AMV_VF_BOOL|a_AMV_VF_VIP */
   'p','o','s','i','x','\0',
   /* 184. [2390]+18 print-alternatives, a_AMV_VF_BOOL */
   'p','r','i','n','t','-','a','l','t','e','r','n','a','t','i','v','e','s','\0',
   /* 185. [2409]+6 prompt, a_AMV_VF_I3VAL */
   'p','r','o','m','p','t','\0',
   /* 186. [2416]+7 prompt2, a_AMV_VF_I3VAL */
   'p','r','o','m','p','t','2','\0',
   /* 187. [2424]+5 quiet, a_AMV_VF_BOOL */
   'q','u','i','e','t','\0',
   /* 188. [2430]+5 quote */
   'q','u','o','t','e','\0',
   /* 189. [2436]+12 quote-add-cc, a_AMV_VF_BOOL */
   'q','u','o','t','e','-','a','d','d','-','c','c','\0',
   /* 190. [2449]+19 quote-as-attachment, a_AMV_VF_BOOL */
   'q','u','o','t','e','-','a','s','-','a','t','t','a','c','h','m','e','n','t','\0',
   /* 191. [2469]+11 quote-chars, a_AMV_VF_VIP|a_AMV_VF_DEFVAL|a_AMV_VF_NOTEMPTY */
   'q','u','o','t','e','-','c','h','a','r','s','\0',
   /* 192. [2481]+10 quote-fold */
   'q','u','o','t','e','-','f','o','l','d','\0',
   /* 193. [2492]+17 quote-inject-head */
   'q','u','o','t','e','-','i','n','j','e','c','t','-','h','e','a','d','\0',
   /* 194. [2510]+17 quote-inject-tail */
   'q','u','o','t','e','-','i','n','j','e','c','t','-','t','a','i','l','\0',
   /* 195. [2528]+17 r-option-implicit, a_AMV_VF_BOOL */
   'r','-','o','p','t','i','o','n','-','i','m','p','l','i','c','i','t','\0',
   /* 196. [2546]+16 recipients-in-cc, a_AMV_VF_BOOL */
   'r','e','c','i','p','i','e','n','t','s','-','i','n','-','c','c','\0',
   /* 197. [2563]+6 record */
   'r','e','c','o','r','d','\0',
   /* 198. [2570]+12 record-files, a_AMV_VF_BOOL */
   'r','e','c','o','r','d','-','f','i','l','e','s','\0',
   /* 199. [2583]+13 record-resent, a_AMV_VF_BOOL */
   'r','e','c','o','r','d','-','r','e','s','e','n','t','\0',
   /* 200. [2597]+21 reply-in-same-charset, a_AMV_VF_BOOL */
   'r','e','p','l','y','-','i','n','-','s','a','m','e','-','c','h','a','r','s','e','t','\0',
   /* 201. [2619]+13 reply-strings */
   'r','e','p','l','y','-','s','t','r','i','n','g','s','\0',
   /* 202. [2633]+7 replyto, a_AMV_VF_NOTEMPTY|a_AMV_VF_OBSOLETE */
   'r','e','p','l','y','t','o','\0',
   /* 203. [2641]+8 reply-to, a_AMV_VF_NOTEMPTY */
   'r','e','p','l','y','-','t','o','\0',
   /* 204. [2650]+15 reply-to-honour */
   'r','e','p','l','y','-','t','o','-','h','o','n','o','u','r','\0',
   /* 205. [2666]+16 reply-to-swap-in */
   'r','e','p','l','y','-','t','o','-','s','w','a','p','-','i','n','\0',
   /* 206. [2683]+17 rfc822-body-from_, a_AMV_VF_BOOL */
   'r','f','c','8','2','2','-','b','o','d','y','-','f','r','o','m','_','\0',
   /* 207. [2701]+5 SHELL, a_AMV_VF_DEFVAL|a_AMV_VF_IMPORT|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY */
   'S','H','E','L','L','\0',
   /* 208. [2707]+5 SYSV3, a_AMV_VF_BOOL|a_AMV_VF_ENV|a_AMV_VF_OBSOLETE */
   'S','Y','S','V','3','\0',
   /* 209. [2713]+4 save, a_AMV_VF_BOOL|a_AMV_VF_I3VAL */
   's','a','v','e','\0',
   /* 210. [2718]+6 screen, a_AMV_VF_NOTEMPTY|a_AMV_VF_POSNUM */
   's','c','r','e','e','n','\0',
   /* 211. [2725]+13 searchheaders, a_AMV_VF_BOOL */
   's','e','a','r','c','h','h','e','a','d','e','r','s','\0',
   /* 212. [2739]+12 sendcharsets, a_AMV_VF_VIP */
   's','e','n','d','c','h','a','r','s','e','t','s','\0',
   /* 213. [2752]+28 sendcharsets-else-ttycharset, a_AMV_VF_BOOL */
   's','e','n','d','c','h','a','r','s','e','t','s','-','e','l','s','e','-','t','t','y','c','h','a','r','s','e','t','\0',
   /* 214. [2781]+6 sender, a_AMV_VF_VIP */
   's','e','n','d','e','r','\0',
   /* 215. [2788]+8 sendmail, a_AMV_VF_OBSOLETE */
   's','e','n','d','m','a','i','l','\0',
   /* 216. [2797]+18 sendmail-arguments, a_AMV_VF_OBSOLETE */
   's','e','n','d','m','a','i','l','-','a','r','g','u','m','e','n','t','s','\0',
   /* 217. [2816]+29 sendmail-no-default-arguments, a_AMV_VF_BOOL|a_AMV_VF_OBSOLETE */
   's','e','n','d','m','a','i','l','-','n','o','-','d','e','f','a','u','l','t','-','a','r','g','u','m','e','n','t','s','\0',
   /* 218. [2846]+17 sendmail-progname, a_AMV_VF_OBSOLETE */
   's','e','n','d','m','a','i','l','-','p','r','o','g','n','a','m','e','\0',
   /* 219. [2864]+8 sendwait, a_AMV_VF_I3VAL */
   's','e','n','d','w','a','i','t','\0',
   /* 220. [2873]+8 showlast, a_AMV_VF_BOOL */
   's','h','o','w','l','a','s','t','\0',
   /* 221. [2882]+8 showname, a_AMV_VF_BOOL */
   's','h','o','w','n','a','m','e','\0',
   /* 222. [2891]+6 showto, a_AMV_VF_BOOL */
   's','h','o','w','t','o','\0',
   /* 223. [2898]+4 Sign */
   'S','i','g','n','\0',
   /* 224. [2903]+4 sign */
   's','i','g','n','\0',
   /* 225. [2908]+9 signature, a_AMV_VF_OBSOLETE */
   's','i','g','n','a','t','u','r','e','\0',
   /* 226. [2918]+13 skipemptybody, a_AMV_VF_BOOL|a_AMV_VF_VIP */
   's','k','i','p','e','m','p','t','y','b','o','d','y','\0',
   /* 227. [2932]+12 smime-ca-dir */
   's','m','i','m','e','-','c','a','-','d','i','r','\0',
   /* 228. [2945]+13 smime-ca-file */
   's','m','i','m','e','-','c','a','-','f','i','l','e','\0',
   /* 229. [2959]+14 smime-ca-flags */
   's','m','i','m','e','-','c','a','-','f','l','a','g','s','\0',
   /* 230. [2974]+20 smime-ca-no-defaults, a_AMV_VF_BOOL */
   's','m','i','m','e','-','c','a','-','n','o','-','d','e','f','a','u','l','t','s','\0',
   /* 231. [2995]+12 smime-cipher, a_AMV_VF_CHAIN */
   's','m','i','m','e','-','c','i','p','h','e','r','\0',
   /* 232. [3008]+13 smime-crl-dir */
   's','m','i','m','e','-','c','r','l','-','d','i','r','\0',
   /* 233. [3022]+14 smime-crl-file */
   's','m','i','m','e','-','c','r','l','-','f','i','l','e','\0',
   /* 234. [3037]+13 smime-encrypt, a_AMV_VF_CHAIN */
   's','m','i','m','e','-','e','n','c','r','y','p','t','\0',
   /* 235. [3051]+22 smime-force-encryption, a_AMV_VF_BOOL */
   's','m','i','m','e','-','f','o','r','c','e','-','e','n','c','r','y','p','t','i','o','n','\0',
   /* 236. [3074]+19 smime-no-default-ca, a_AMV_VF_BOOL|a_AMV_VF_OBSOLETE */
   's','m','i','m','e','-','n','o','-','d','e','f','a','u','l','t','-','c','a','\0',
   /* 237. [3094]+10 smime-sign, a_AMV_VF_BOOL */
   's','m','i','m','e','-','s','i','g','n','\0',
   /* 238. [3105]+15 smime-sign-cert, a_AMV_VF_CHAIN */
   's','m','i','m','e','-','s','i','g','n','-','c','e','r','t','\0',
   /* 239. [3121]+17 smime-sign-digest, a_AMV_VF_CHAIN */
   's','m','i','m','e','-','s','i','g','n','-','d','i','g','e','s','t','\0',
   /* 240. [3139]+24 smime-sign-include-certs, a_AMV_VF_CHAIN */
   's','m','i','m','e','-','s','i','g','n','-','i','n','c','l','u','d','e','-','c','e','r','t','s','\0',
   /* 241. [3164]+25 smime-sign-message-digest, a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE */
   's','m','i','m','e','-','s','i','g','n','-','m','e','s','s','a','g','e','-','d','i','g','e','s','t','\0',
   /* 242. [3190]+4 smtp, a_AMV_VF_OBSOLETE */
   's','m','t','p','\0',
   /* 243. [3195]+9 smtp-auth, a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE */
   's','m','t','p','-','a','u','t','h','\0',
   /* 244. [3205]+18 smtp-auth-password, a_AMV_VF_OBSOLETE */
   's','m','t','p','-','a','u','t','h','-','p','a','s','s','w','o','r','d','\0',
   /* 245. [3224]+14 smtp-auth-user, a_AMV_VF_OBSOLETE */
   's','m','t','p','-','a','u','t','h','-','u','s','e','r','\0',
   /* 246. [3239]+11 smtp-config, a_AMV_VF_CHAIN */
   's','m','t','p','-','c','o','n','f','i','g','\0',
   /* 247. [3251]+9 smtp-from, a_AMV_VF_VIP|a_AMV_VF_CHAIN */
   's','m','t','p','-','f','r','o','m','\0',
   /* 248. [3261]+13 smtp-hostname, a_AMV_VF_VIP|a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE */
   's','m','t','p','-','h','o','s','t','n','a','m','e','\0',
   /* 249. [3275]+17 smtp-use-starttls, a_AMV_VF_BOOL|a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE */
   's','m','t','p','-','u','s','e','-','s','t','a','r','t','t','l','s','\0',
   /* 250. [3293]+12 SOCKS5_PROXY, a_AMV_VF_VIP|a_AMV_VF_IMPORT|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY */
   'S','O','C','K','S','5','_','P','R','O','X','Y','\0',
   /* 251. [3306]+17 SOURCE_DATE_EPOCH, a_AMV_VF_RDONLY|a_AMV_VF_IMPORT|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY|a_AMV_VF_POSNUM */
   'S','O','U','R','C','E','_','D','A','T','E','_','E','P','O','C','H','\0',
   /* 252. [3324]+22 socket-connect-timeout, a_AMV_VF_POSNUM */
   's','o','c','k','e','t','-','c','o','n','n','e','c','t','-','t','i','m','e','o','u','t','\0',
   /* 253. [3347]+11 socks-proxy, a_AMV_VF_VIP|a_AMV_VF_NOTEMPTY|a_AMV_VF_CHAIN */
   's','o','c','k','s','-','p','r','o','x','y','\0',
   /* 254. [3359]+14 spam-interface */
   's','p','a','m','-','i','n','t','e','r','f','a','c','e','\0',
   /* 255. [3374]+12 spam-maxsize, a_AMV_VF_NOTEMPTY|a_AMV_VF_POSNUM */
   's','p','a','m','-','m','a','x','s','i','z','e','\0',
   /* 256. [3387]+13 spamc-command */
   's','p','a','m','c','-','c','o','m','m','a','n','d','\0',
   /* 257. [3401]+15 spamc-arguments */
   's','p','a','m','c','-','a','r','g','u','m','e','n','t','s','\0',
   /* 258. [3417]+10 spamc-user */
   's','p','a','m','c','-','u','s','e','r','\0',
   /* 259. [3428]+14 spamfilter-ham */
   's','p','a','m','f','i','l','t','e','r','-','h','a','m','\0',
   /* 260. [3443]+16 spamfilter-noham */
   's','p','a','m','f','i','l','t','e','r','-','n','o','h','a','m','\0',
   /* 261. [3460]+17 spamfilter-nospam */
   's','p','a','m','f','i','l','t','e','r','-','n','o','s','p','a','m','\0',
   /* 262. [3478]+15 spamfilter-rate */
   's','p','a','m','f','i','l','t','e','r','-','r','a','t','e','\0',
   /* 263. [3494]+25 spamfilter-rate-scanscore */
   's','p','a','m','f','i','l','t','e','r','-','r','a','t','e','-','s','c','a','n','s','c','o','r','e','\0',
   /* 264. [3520]+15 spamfilter-spam */
   's','p','a','m','f','i','l','t','e','r','-','s','p','a','m','\0',
   /* 265. [3536]+10 ssl-ca-dir, a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE */
   's','s','l','-','c','a','-','d','i','r','\0',
   /* 266. [3547]+11 ssl-ca-file, a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE */
   's','s','l','-','c','a','-','f','i','l','e','\0',
   /* 267. [3559]+12 ssl-ca-flags, a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE */
   's','s','l','-','c','a','-','f','l','a','g','s','\0',
   /* 268. [3572]+18 ssl-ca-no-defaults, a_AMV_VF_BOOL|a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE */
   's','s','l','-','c','a','-','n','o','-','d','e','f','a','u','l','t','s','\0',
   /* 269. [3591]+8 ssl-cert, a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE */
   's','s','l','-','c','e','r','t','\0',
   /* 270. [3600]+15 ssl-cipher-list, a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE */
   's','s','l','-','c','i','p','h','e','r','-','l','i','s','t','\0',
   /* 271. [3616]+15 ssl-config-file, a_AMV_VF_OBSOLETE */
   's','s','l','-','c','o','n','f','i','g','-','f','i','l','e','\0',
   /* 272. [3632]+17 ssl-config-module, a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE */
   's','s','l','-','c','o','n','f','i','g','-','m','o','d','u','l','e','\0',
   /* 273. [3650]+16 ssl-config-pairs, a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE */
   's','s','l','-','c','o','n','f','i','g','-','p','a','i','r','s','\0',
   /* 274. [3667]+10 ssl-curves, a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE */
   's','s','l','-','c','u','r','v','e','s','\0',
   /* 275. [3678]+11 ssl-crl-dir, a_AMV_VF_OBSOLETE */
   's','s','l','-','c','r','l','-','d','i','r','\0',
   /* 276. [3690]+12 ssl-crl-file, a_AMV_VF_OBSOLETE */
   's','s','l','-','c','r','l','-','f','i','l','e','\0',
   /* 277. [3703]+12 ssl-features, a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL|a_AMV_VF_OBSOLETE */
   's','s','l','-','f','e','a','t','u','r','e','s','\0',
   /* 278. [3716]+7 ssl-key, a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE */
   's','s','l','-','k','e','y','\0',
   /* 279. [3724]+10 ssl-method, a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE */
   's','s','l','-','m','e','t','h','o','d','\0',
   /* 280. [3735]+17 ssl-no-default-ca, a_AMV_VF_BOOL|a_AMV_VF_OBSOLETE */
   's','s','l','-','n','o','-','d','e','f','a','u','l','t','-','c','a','\0',
   /* 281. [3753]+12 ssl-protocol, a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE */
   's','s','l','-','p','r','o','t','o','c','o','l','\0',
   /* 282. [3766]+12 ssl-rand-egd, a_AMV_VF_OBSOLETE */
   's','s','l','-','r','a','n','d','-','e','g','d','\0',
   /* 283. [3779]+13 ssl-rand-file, a_AMV_VF_OBSOLETE */
   's','s','l','-','r','a','n','d','-','f','i','l','e','\0',
   /* 284. [3793]+10 ssl-verify, a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE */
   's','s','l','-','v','e','r','i','f','y','\0',
   /* 285. [3804]+10 stealthmua */
   's','t','e','a','l','t','h','m','u','a','\0',
   /* 286. [3815]+13 system-mailrc, a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL */
   's','y','s','t','e','m','-','m','a','i','l','r','c','\0',
   /* 287. [3829]+4 TERM, a_AMV_VF_ENV */
   'T','E','R','M','\0',
   /* 288. [3834]+6 TMPDIR, a_AMV_VF_VIP|a_AMV_VF_DEFVAL|a_AMV_VF_IMPORT|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY */
   'T','M','P','D','I','R','\0',
   /* 289. [3841]+7 termcap */
   't','e','r','m','c','a','p','\0',
   /* 290. [3849]+15 termcap-ca-mode */
   't','e','r','m','c','a','p','-','c','a','-','m','o','d','e','\0',
   /* 291. [3865]+15 termcap-disable, a_AMV_VF_BOOL */
   't','e','r','m','c','a','p','-','d','i','s','a','b','l','e','\0',
   /* 292. [3881]+10 tls-ca-dir, a_AMV_VF_CHAIN */
   't','l','s','-','c','a','-','d','i','r','\0',
   /* 293. [3892]+11 tls-ca-file, a_AMV_VF_CHAIN */
   't','l','s','-','c','a','-','f','i','l','e','\0',
   /* 294. [3904]+12 tls-ca-flags, a_AMV_VF_CHAIN */
   't','l','s','-','c','a','-','f','l','a','g','s','\0',
   /* 295. [3917]+18 tls-ca-no-defaults, a_AMV_VF_BOOL|a_AMV_VF_CHAIN */
   't','l','s','-','c','a','-','n','o','-','d','e','f','a','u','l','t','s','\0',
   /* 296. [3936]+15 tls-config-file */
   't','l','s','-','c','o','n','f','i','g','-','f','i','l','e','\0',
   /* 297. [3952]+17 tls-config-module, a_AMV_VF_CHAIN */
   't','l','s','-','c','o','n','f','i','g','-','m','o','d','u','l','e','\0',
   /* 298. [3970]+16 tls-config-pairs, a_AMV_VF_CHAIN */
   't','l','s','-','c','o','n','f','i','g','-','p','a','i','r','s','\0',
   /* 299. [3987]+11 tls-crl-dir */
   't','l','s','-','c','r','l','-','d','i','r','\0',
   /* 300. [3999]+12 tls-crl-file */
   't','l','s','-','c','r','l','-','f','i','l','e','\0',
   /* 301. [4012]+12 tls-features, a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL */
   't','l','s','-','f','e','a','t','u','r','e','s','\0',
   /* 302. [4025]+15 tls-fingerprint, a_AMV_VF_CHAIN */
   't','l','s','-','f','i','n','g','e','r','p','r','i','n','t','\0',
   /* 303. [4041]+22 tls-fingerprint-digest, a_AMV_VF_CHAIN */
   't','l','s','-','f','i','n','g','e','r','p','r','i','n','t','-','d','i','g','e','s','t','\0',
   /* 304. [4064]+13 tls-rand-file */
   't','l','s','-','r','a','n','d','-','f','i','l','e','\0',
   /* 305. [4078]+10 tls-verify, a_AMV_VF_CHAIN */
   't','l','s','-','v','e','r','i','f','y','\0',
   /* 306. [4089]+8 toplines, a_AMV_VF_DEFVAL|a_AMV_VF_NOTEMPTY|a_AMV_VF_NUM */
   't','o','p','l','i','n','e','s','\0',
   /* 307. [4098]+10 topsqueeze, a_AMV_VF_BOOL */
   't','o','p','s','q','u','e','e','z','e','\0',
   /* 308. [4109]+10 ttycharset, a_AMV_VF_VIP|a_AMV_VF_DEFVAL|a_AMV_VF_NOTEMPTY */
   't','t','y','c','h','a','r','s','e','t','\0',
   /* 309. [4120]+15 typescript-mode, a_AMV_VF_BOOL|a_AMV_VF_VIP */
   't','y','p','e','s','c','r','i','p','t','-','m','o','d','e','\0',
   /* 310. [4136]+4 USER, a_AMV_VF_RDONLY|a_AMV_VF_IMPORT|a_AMV_VF_ENV */
   'U','S','E','R','\0',
   /* 311. [4141]+5 umask, a_AMV_VF_VIP|a_AMV_VF_NODEL|a_AMV_VF_I3VAL|a_AMV_VF_POSNUM */
   'u','m','a','s','k','\0',
   /* 312. [4147]+4 user, a_AMV_VF_NOTEMPTY|a_AMV_VF_CHAIN */
   'u','s','e','r','\0',
   /* 313. [4152]+6 VISUAL, a_AMV_VF_DEFVAL|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY */
   'V','I','S','U','A','L','\0',
   /* 314. [4159]+10 v15-compat, a_AMV_VF_I3VAL */
   'v','1','5','-','c','o','m','p','a','t','\0',
   /* 315. [4170]+7 verbose, a_AMV_VF_VIP|a_AMV_VF_POSNUM */
   'v','e','r','b','o','s','e','\0',
   /* 316. [4178]+7 version, a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL */
   'v','e','r','s','i','o','n','\0',
   /* 317. [4186]+12 version-date, a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL */
   'v','e','r','s','i','o','n','-','d','a','t','e','\0',
   /* 318. [4199]+14 version-hexnum, a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL|a_AMV_VF_POSNUM */
   'v','e','r','s','i','o','n','-','h','e','x','n','u','m','\0',
   /* 319. [4214]+13 version-major, a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL|a_AMV_VF_POSNUM */
   'v','e','r','s','i','o','n','-','m','a','j','o','r','\0',
   /* 320. [4228]+13 version-minor, a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL|a_AMV_VF_POSNUM */
   'v','e','r','s','i','o','n','-','m','i','n','o','r','\0',
   /* 321. [4242]+14 version-update, a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL|a_AMV_VF_POSNUM */
   'v','e','r','s','i','o','n','-','u','p','d','a','t','e','\0',
   /* 322. [4257]+15 writebackedited, a_AMV_VF_BOOL */
   'w','r','i','t','e','b','a','c','k','e','d','i','t','e','d','\0',
   /* 323. [4273]+12 disconnected, a_AMV_VF_BOOL|a_AMV_VF_CHAIN */
   'd','i','s','c','o','n','n','e','c','t','e','d','\0',
   /* 324. [4286]+9 imap-auth, a_AMV_VF_CHAIN */
   'i','m','a','p','-','a','u','t','h','\0',
   /* 325. [4296]+10 imap-cache */
   'i','m','a','p','-','c','a','c','h','e','\0',
   /* 326. [4307]+10 imap-delim, a_AMV_VF_CHAIN */
   'i','m','a','p','-','d','e','l','i','m','\0',
   /* 327. [4318]+14 imap-keepalive, a_AMV_VF_CHAIN */
   'i','m','a','p','-','k','e','e','p','a','l','i','v','e','\0',
   /* 328. [4333]+15 imap-list-depth */
   'i','m','a','p','-','l','i','s','t','-','d','e','p','t','h','\0',
   /* 329. [4349]+17 imap-use-starttls, a_AMV_VF_BOOL|a_AMV_VF_CHAIN */
   'i','m','a','p','-','u','s','e','-','s','t','a','r','t','t','l','s','\0',
   /* 330. [4367]+13 _S_MAILX_TEST, a_AMV_VF_ENV */
   '_','S','_','M','A','I','L','X','_','T','E','S','T','\0',
};
#define a_AMV_VAR_NAME_KEY_MAXOFF 4381u
#define a_AMV_VAR_HAS_OBSOLETE

CTA(a_AMV_VF_NONE == 0, "Value not 0 as expected");
static struct a_amv_var_map const a_amv_var_map[] = {
   {227278652u, 0u, a_AMV_VF_NONE|a_AMV_VF_RDONLY|a_AMV_VF_NODEL|a_AMV_VF_NOLOPTS},   /* --special-param */
   {154495572u, 16u, a_AMV_VF_NONE|a_AMV_VF_RDONLY|a_AMV_VF_NODEL|a_AMV_VF_NOLOPTS},   /* ? */
   {80927451u, 18u, a_AMV_VF_NONE|a_AMV_VF_RDONLY|a_AMV_VF_NODEL|a_AMV_VF_NOLOPTS},   /* ! */
   {3357062669u, 20u, a_AMV_VF_NONE|a_AMV_VF_RDONLY|a_AMV_VF_NODEL|a_AMV_VF_NOLOPTS},   /* account */
   {493847641u, 28u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* add-file-recipients */
   {3300482900u, 48u, a_AMV_VF_NONE|a_AMV_VF_OBSOLETE},   /* agent-shell-lookup */
   {494283953u, 67u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* allnet */
   {1058320012u, 74u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* append */
   {2551535105u, 81u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_VIP},   /* ask */
   {3811864832u, 85u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* askatend */
   {996153470u, 94u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* askattach */
   {1888769187u, 104u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* askbcc */
   {116464337u, 111u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* askcc */
   {2284472721u, 117u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* asksign */
   {3082104315u, 125u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* asksend */
   {311620u, 133u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_I3VAL},   /* asksub */
   {745929243u, 140u, a_AMV_VF_NONE},   /* attrlist */
   {4253309083u, 149u, a_AMV_VF_NONE},   /* autobcc */
   {1364365036u, 157u, a_AMV_VF_NONE},   /* autocc */
   {3614598233u, 164u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* autocollapse */
   {1227119359u, 177u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* autoprint */
   {2751932733u, 187u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_OBSOLETE},   /* autothread */
   {795112500u, 198u, a_AMV_VF_NONE},   /* autosort */
   {2505240952u, 207u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* bang */
   {2561950027u, 212u, a_AMV_VF_NONE|a_AMV_VF_VIP|a_AMV_VF_NOTEMPTY|a_AMV_VF_POSNUM|a_AMV_VF_OBSOLETE},   /* bind-timeout */
   {3708435556u, 225u, a_AMV_VF_NONE|a_AMV_VF_DEFVAL|a_AMV_VF_NOTEMPTY|a_AMV_VF_POSNUM},   /* bind-inter-byte-timeout */
   {3166102662u, 249u, a_AMV_VF_NONE|a_AMV_VF_NOTEMPTY|a_AMV_VF_POSNUM},   /* bind-inter-key-timeout */
   {2594579305u, 272u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_OBSOLETE},   /* bsdannounce */
   {3899593563u, 284u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* bsdcompat */
   {4175238939u, 294u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* bsdflags */
   {544406618u, 303u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* bsdheadline */
   {3124538195u, 315u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* bsdmsgs */
   {4225922782u, 323u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* bsdorder */
   {4282337783u, 332u, a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL},   /* build-cc */
   {580749460u, 341u, a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL},   /* build-ld */
   {855442780u, 350u, a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL},   /* build-os */
   {826549826u, 359u, a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL},   /* build-rest */
   {2160670167u, 370u, a_AMV_VF_NONE|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY|a_AMV_VF_POSNUM},   /* COLUMNS */
   {1152129485u, 378u, a_AMV_VF_NONE|a_AMV_VF_VIP|a_AMV_VF_DEFVAL|a_AMV_VF_NOTEMPTY},   /* charset-7bit */
   {3559906218u, 391u, a_AMV_VF_NONE|a_AMV_VF_VIP|a_AMV_VF_DEFVAL|a_AMV_VF_NOTEMPTY},   /* charset-8bit */
   {2813999997u, 404u, a_AMV_VF_NONE|a_AMV_VF_VIP},   /* charset-unknown-8bit */
   {3267913060u, 425u, a_AMV_VF_NONE},   /* cmd */
   {287190100u, 429u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* colour-disable */
   {846327017u, 444u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_OBSOLETE},   /* colour-pager */
   {1122098125u, 457u, a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL},   /* contact-mail */
   {1124592011u, 470u, a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL},   /* contact-web */
   {2597875993u, 482u, a_AMV_VF_NONE|a_AMV_VF_DEFVAL},   /* content-description-forwarded-message */
   {1060377975u, 520u, a_AMV_VF_NONE|a_AMV_VF_DEFVAL},   /* content-description-quote-attachment */
   {3459029433u, 557u, a_AMV_VF_NONE|a_AMV_VF_DEFVAL},   /* content-description-smime-message */
   {2186292469u, 591u, a_AMV_VF_NONE|a_AMV_VF_DEFVAL},   /* content-description-smime-signature */
   {2999592795u, 627u, a_AMV_VF_NONE|a_AMV_VF_POSNUM},   /* crt */
   {2781333397u, 631u, a_AMV_VF_NONE|a_AMV_VF_VIP},   /* customhdr */
   {2415640462u, 641u, a_AMV_VF_NONE|a_AMV_VF_DEFVAL|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY},   /* DEAD */
   {1827964010u, 646u, a_AMV_VF_NONE|a_AMV_VF_I3VAL},   /* datefield */
   {393145609u, 656u, a_AMV_VF_NONE|a_AMV_VF_I3VAL},   /* datefield-markout-older */
   {3577320874u, 680u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_VIP},   /* debug */
   {2967068228u, 686u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* disposition-notification-send */
   {1214666681u, 716u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* dot */
   {160284180u, 720u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* dotlock-disable */
   {1694953629u, 736u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_OBSOLETE},   /* dotlock-ignore-error */
   {1242446766u, 757u, a_AMV_VF_NONE|a_AMV_VF_DEFVAL|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY},   /* EDITOR */
   {1594887356u, 764u, a_AMV_VF_NONE},   /* editalong */
   {3883110174u, 774u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* editheaders */
   {2988505335u, 786u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* emptystart */
   {3787987885u, 797u, a_AMV_VF_NONE|a_AMV_VF_OBSOLETE},   /* encoding */
   {558368469u, 806u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* errexit */
   {2009839120u, 814u, a_AMV_VF_NONE|a_AMV_VF_DEFVAL|a_AMV_VF_NOTEMPTY|a_AMV_VF_POSNUM},   /* errors-limit */
   {226969255u, 827u, a_AMV_VF_NONE|a_AMV_VF_DEFVAL},   /* escape */
   {290884965u, 834u, a_AMV_VF_NONE},   /* expandaddr */
   {1137944571u, 845u, a_AMV_VF_NONE|a_AMV_VF_NOTEMPTY},   /* expandaddr-domaincheck */
   {246331225u, 868u, a_AMV_VF_NONE},   /* expandargv */
   {2405915007u, 879u, a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL},   /* features */
   {396387274u, 888u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* flipr */
   {1247301214u, 894u, a_AMV_VF_NONE|a_AMV_VF_VIP},   /* folder */
   {380489737u, 901u, a_AMV_VF_NONE|a_AMV_VF_RDONLY|a_AMV_VF_NODEL},   /* folder-resolved */
   {3313520922u, 917u, a_AMV_VF_NONE},   /* folder-hook */
   {724424027u, 929u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* followup-to */
   {207519379u, 941u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* followup-to-add-cc */
   {4130486046u, 960u, a_AMV_VF_NONE},   /* followup-to-honour */
   {1845222365u, 979u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* forward-add-cc */
   {1502086073u, 994u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* forward-as-attachment */
   {3821632635u, 1016u, a_AMV_VF_NONE},   /* forward-inject-head */
   {2452299938u, 1036u, a_AMV_VF_NONE},   /* forward-inject-tail */
   {602154724u, 1056u, a_AMV_VF_NONE|a_AMV_VF_VIP},   /* from */
   {3763021371u, 1061u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* fullnames */
   {1982641597u, 1071u, a_AMV_VF_NONE|a_AMV_VF_OBSOLETE},   /* fwdheading */
   {2741985269u, 1082u, a_AMV_VF_NONE|a_AMV_VF_VIP|a_AMV_VF_NODEL|a_AMV_VF_IMPORT|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY},   /* HOME */
   {64545433u, 1087u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_I3VAL},   /* header */
   {3501927842u, 1094u, a_AMV_VF_NONE},   /* headline */
   {1804975779u, 1103u, a_AMV_VF_NONE},   /* headline-bidi */
   {1481160096u, 1117u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* headline-plain */
   {912008308u, 1132u, a_AMV_VF_NONE},   /* history-file */
   {3026632813u, 1145u, a_AMV_VF_NONE},   /* history-gabby */
   {2385770127u, 1159u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* history-gabby-persist */
   {525831433u, 1181u, a_AMV_VF_NONE|a_AMV_VF_NOTEMPTY|a_AMV_VF_POSNUM},   /* history-size */
   {2672153034u, 1194u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* hold */
   {2616319247u, 1199u, a_AMV_VF_NONE|a_AMV_VF_VIP},   /* hostname */
   {978281147u, 1208u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* idna-disable */
   {1104992522u, 1221u, a_AMV_VF_NONE|a_AMV_VF_VIP|a_AMV_VF_DEFVAL},   /* ifs */
   {3356804030u, 1225u, a_AMV_VF_NONE|a_AMV_VF_VIP|a_AMV_VF_RDONLY|a_AMV_VF_NODEL|a_AMV_VF_I3VAL},   /* ifs-ws */
   {728948543u, 1232u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* ignore */
   {2906377970u, 1239u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* ignoreeof */
   {2604688712u, 1249u, a_AMV_VF_NONE},   /* inbox */
   {1338595061u, 1255u, a_AMV_VF_NONE|a_AMV_VF_DEFVAL},   /* indentprefix */
   {143835737u, 1268u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* keep */
   {4104264131u, 1273u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* keep-content-length */
   {174649434u, 1293u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* keepsave */
   {2145171579u, 1302u, a_AMV_VF_NONE|a_AMV_VF_VIP|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY},   /* LANG */
   {1678977712u, 1307u, a_AMV_VF_NONE|a_AMV_VF_VIP|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY},   /* LC_ALL */
   {1182282912u, 1314u, a_AMV_VF_NONE|a_AMV_VF_VIP|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY},   /* LC_CTYPE */
   {2376678931u, 1323u, a_AMV_VF_NONE|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY|a_AMV_VF_POSNUM},   /* LINES */
   {1848015380u, 1329u, a_AMV_VF_NONE|a_AMV_VF_DEFVAL|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY},   /* LISTER */
   {3871590672u, 1336u, a_AMV_VF_NONE|a_AMV_VF_RDONLY|a_AMV_VF_IMPORT|a_AMV_VF_ENV},   /* LOGNAME */
   {3705547024u, 1344u, a_AMV_VF_NONE|a_AMV_VF_NOTEMPTY},   /* line-editor-config */
   {3059025987u, 1363u, a_AMV_VF_NONE|a_AMV_VF_DEFVAL},   /* line-editor-cpl-word-breaks */
   {3293963057u, 1391u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* line-editor-disable */
   {3853763107u, 1411u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* line-editor-no-defaults */
   {1789070192u, 1435u, a_AMV_VF_NONE|a_AMV_VF_NODEL|a_AMV_VF_I3VAL},   /* log-prefix */
   {1789157842u, 1446u, a_AMV_VF_NONE|a_AMV_VF_ENV},   /* MAIL */
   {2736404651u, 1451u, a_AMV_VF_NONE|a_AMV_VF_DEFVAL|a_AMV_VF_IMPORT|a_AMV_VF_ENV},   /* MAILCAPS */
   {3252715507u, 1460u, a_AMV_VF_NONE|a_AMV_VF_DEFVAL|a_AMV_VF_IMPORT|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY},   /* MAILRC */
   {3506381864u, 1467u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_IMPORT|a_AMV_VF_ENV},   /* MAILX_NO_SYSTEM_RC */
   {81016594u, 1486u, a_AMV_VF_NONE|a_AMV_VF_DEFVAL|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY},   /* MBOX */
   {2864198801u, 1491u, a_AMV_VF_NONE|a_AMV_VF_RDONLY|a_AMV_VF_NODEL|a_AMV_VF_NOLOPTS},   /* mailbox-basename */
   {3586483916u, 1508u, a_AMV_VF_NONE|a_AMV_VF_RDONLY|a_AMV_VF_NODEL|a_AMV_VF_NOLOPTS},   /* mailbox-display */
   {431868467u, 1524u, a_AMV_VF_NONE|a_AMV_VF_RDONLY|a_AMV_VF_NODEL|a_AMV_VF_NOLOPTS},   /* mailbox-resolved */
   {3619987079u, 1541u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* mailcap-disable */
   {1809788732u, 1557u, a_AMV_VF_NONE|a_AMV_VF_NOTEMPTY},   /* mailx-extra-rc */
   {3344360316u, 1572u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* markanswered */
   {97960896u, 1585u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_I3VAL},   /* mbox-fcc-and-pcc */
   {1206644946u, 1602u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* mbox-rfc4155 */
   {411705792u, 1615u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_VIP},   /* memdebug */
   {2924780567u, 1624u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* message-id-disable */
   {3508650772u, 1643u, a_AMV_VF_NONE},   /* message-inject-head */
   {2318901230u, 1663u, a_AMV_VF_NONE},   /* message-inject-tail */
   {3755204636u, 1683u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* metoo */
   {1123775568u, 1689u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* mime-allow-text-controls */
   {1016573875u, 1714u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* mime-alternative-favour-rich */
   {1894749336u, 1743u, a_AMV_VF_NONE|a_AMV_VF_POSNUM},   /* mime-counter-evidence */
   {7077405u, 1765u, a_AMV_VF_NONE},   /* mime-encoding */
   {212277572u, 1779u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* mime-force-sendout */
   {3037097698u, 1798u, a_AMV_VF_NONE},   /* mimetypes-load-control */
   {553443582u, 1821u, a_AMV_VF_NONE|a_AMV_VF_DEFVAL|a_AMV_VF_NOTEMPTY},   /* mta */
   {832650830u, 1825u, a_AMV_VF_NONE|a_AMV_VF_NOTEMPTY},   /* mta-aliases */
   {2950745266u, 1837u, a_AMV_VF_NONE},   /* mta-arguments */
   {3777230887u, 1851u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* mta-no-default-arguments */
   {1537483713u, 1876u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* mta-no-receiver-arguments */
   {2122434769u, 1902u, a_AMV_VF_NONE|a_AMV_VF_DEFVAL|a_AMV_VF_NOTEMPTY},   /* mta-argv0 */
   {3661122784u, 1912u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* mta-bcc-ok */
   {3872053044u, 1923u, a_AMV_VF_NONE|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY|a_AMV_VF_OBSOLETE},   /* NAIL_EXTRA_RC */
   {297169422u, 1937u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_IMPORT|a_AMV_VF_ENV|a_AMV_VF_OBSOLETE},   /* NAIL_NO_SYSTEM_RC */
   {1607860199u, 1955u, a_AMV_VF_NONE|a_AMV_VF_OBSOLETE},   /* NAIL_HEAD */
   {2276529140u, 1965u, a_AMV_VF_NONE|a_AMV_VF_OBSOLETE},   /* NAIL_HISTFILE */
   {3334752474u, 1979u, a_AMV_VF_NONE|a_AMV_VF_NOTEMPTY|a_AMV_VF_NUM|a_AMV_VF_OBSOLETE},   /* NAIL_HISTSIZE */
   {1983079716u, 1993u, a_AMV_VF_NONE|a_AMV_VF_OBSOLETE},   /* NAIL_TAIL */
   {2020589051u, 2003u, a_AMV_VF_NONE|a_AMV_VF_DEFVAL|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY},   /* NETRC */
   {1260217930u, 2009u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_CHAIN},   /* netrc-lookup */
   {3886637952u, 2022u, a_AMV_VF_NONE},   /* netrc-pipe */
   {3651172215u, 2033u, a_AMV_VF_NONE},   /* newfolders */
   {3304640034u, 2044u, a_AMV_VF_NONE},   /* newmail */
   {117356079u, 2052u, a_AMV_VF_NONE|a_AMV_VF_NOTEMPTY},   /* on-account-cleanup */
   {4290007558u, 2071u, a_AMV_VF_NONE|a_AMV_VF_NOTEMPTY},   /* on-compose-cleanup */
   {293825268u, 2090u, a_AMV_VF_NONE|a_AMV_VF_NOTEMPTY},   /* on-compose-enter */
   {2131049871u, 2107u, a_AMV_VF_NONE|a_AMV_VF_NOTEMPTY},   /* on-compose-leave */
   {3562380821u, 2124u, a_AMV_VF_NONE|a_AMV_VF_NOTEMPTY},   /* on-compose-splice */
   {3452672776u, 2142u, a_AMV_VF_NONE|a_AMV_VF_NOTEMPTY},   /* on-compose-splice-shell */
   {1488358487u, 2166u, a_AMV_VF_NONE|a_AMV_VF_NOTEMPTY},   /* on-history-addition */
   {3412211600u, 2186u, a_AMV_VF_NONE|a_AMV_VF_NOTEMPTY},   /* on-main-loop-tick */
   {395906010u, 2204u, a_AMV_VF_NONE|a_AMV_VF_NOTEMPTY},   /* on-program-exit */
   {1767855548u, 2220u, a_AMV_VF_NONE|a_AMV_VF_NOTEMPTY},   /* on-resend-cleanup */
   {2401366305u, 2238u, a_AMV_VF_NONE|a_AMV_VF_NOTEMPTY},   /* on-resend-enter */
   {416513343u, 2254u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* outfolder */
   {1489818949u, 2264u, a_AMV_VF_NONE|a_AMV_VF_DEFVAL|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY},   /* PAGER */
   {2822297945u, 2270u, a_AMV_VF_NONE|a_AMV_VF_NODEL|a_AMV_VF_IMPORT|a_AMV_VF_ENV},   /* PATH */
   {2133454918u, 2275u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_VIP|a_AMV_VF_IMPORT|a_AMV_VF_ENV},   /* POSIXLY_CORRECT */
   {110139073u, 2291u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* page */
   {236033362u, 2296u, a_AMV_VF_NONE|a_AMV_VF_CHAIN},   /* password */
   {1184554264u, 2305u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* piperaw */
   {959912200u, 2313u, a_AMV_VF_NONE|a_AMV_VF_CHAIN},   /* pop3-auth */
   {2157156237u, 2323u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* pop3-bulk-load */
   {3679046711u, 2338u, a_AMV_VF_NONE|a_AMV_VF_NOTEMPTY|a_AMV_VF_POSNUM},   /* pop3-keepalive */
   {1128676729u, 2353u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_CHAIN},   /* pop3-no-apop */
   {403462699u, 2366u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_CHAIN},   /* pop3-use-starttls */
   {2340434703u, 2384u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_VIP},   /* posix */
   {909397219u, 2390u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* print-alternatives */
   {3753422504u, 2409u, a_AMV_VF_NONE|a_AMV_VF_I3VAL},   /* prompt */
   {1957394514u, 2416u, a_AMV_VF_NONE|a_AMV_VF_I3VAL},   /* prompt2 */
   {149149615u, 2424u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* quiet */
   {3721493487u, 2430u, a_AMV_VF_NONE},   /* quote */
   {366442025u, 2436u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* quote-add-cc */
   {1890299439u, 2449u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* quote-as-attachment */
   {4044677414u, 2469u, a_AMV_VF_NONE|a_AMV_VF_VIP|a_AMV_VF_DEFVAL|a_AMV_VF_NOTEMPTY},   /* quote-chars */
   {3595968213u, 2481u, a_AMV_VF_NONE},   /* quote-fold */
   {2640088545u, 2492u, a_AMV_VF_NONE},   /* quote-inject-head */
   {2904204181u, 2510u, a_AMV_VF_NONE},   /* quote-inject-tail */
   {1640115048u, 2528u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* r-option-implicit */
   {188553526u, 2546u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* recipients-in-cc */
   {540723528u, 2563u, a_AMV_VF_NONE},   /* record */
   {146539205u, 2570u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* record-files */
   {2425465309u, 2583u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* record-resent */
   {1513358607u, 2597u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* reply-in-same-charset */
   {1900410726u, 2619u, a_AMV_VF_NONE},   /* reply-strings */
   {2583631056u, 2633u, a_AMV_VF_NONE|a_AMV_VF_NOTEMPTY|a_AMV_VF_OBSOLETE},   /* replyto */
   {1151099134u, 2641u, a_AMV_VF_NONE|a_AMV_VF_NOTEMPTY},   /* reply-to */
   {2823711003u, 2650u, a_AMV_VF_NONE},   /* reply-to-honour */
   {1277335386u, 2666u, a_AMV_VF_NONE},   /* reply-to-swap-in */
   {3620202244u, 2683u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* rfc822-body-from_ */
   {1938020952u, 2701u, a_AMV_VF_NONE|a_AMV_VF_DEFVAL|a_AMV_VF_IMPORT|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY},   /* SHELL */
   {4069714370u, 2707u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_ENV|a_AMV_VF_OBSOLETE},   /* SYSV3 */
   {3498694618u, 2713u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_I3VAL},   /* save */
   {3962019339u, 2718u, a_AMV_VF_NONE|a_AMV_VF_NOTEMPTY|a_AMV_VF_POSNUM},   /* screen */
   {1130371609u, 2725u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* searchheaders */
   {968926480u, 2739u, a_AMV_VF_NONE|a_AMV_VF_VIP},   /* sendcharsets */
   {760633097u, 2752u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* sendcharsets-else-ttycharset */
   {504631978u, 2781u, a_AMV_VF_NONE|a_AMV_VF_VIP},   /* sender */
   {856236114u, 2788u, a_AMV_VF_NONE|a_AMV_VF_OBSOLETE},   /* sendmail */
   {3085354123u, 2797u, a_AMV_VF_NONE|a_AMV_VF_OBSOLETE},   /* sendmail-arguments */
   {1325127300u, 2816u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_OBSOLETE},   /* sendmail-no-default-arguments */
   {3864687553u, 2846u, a_AMV_VF_NONE|a_AMV_VF_OBSOLETE},   /* sendmail-progname */
   {1977567474u, 2864u, a_AMV_VF_NONE|a_AMV_VF_I3VAL},   /* sendwait */
   {3980879360u, 2873u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* showlast */
   {4203664219u, 2882u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* showname */
   {3064935001u, 2891u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* showto */
   {833163053u, 2898u, a_AMV_VF_NONE},   /* Sign */
   {1713520988u, 2903u, a_AMV_VF_NONE},   /* sign */
   {2783766075u, 2908u, a_AMV_VF_NONE|a_AMV_VF_OBSOLETE},   /* signature */
   {534091439u, 2918u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_VIP},   /* skipemptybody */
   {135477722u, 2932u, a_AMV_VF_NONE},   /* smime-ca-dir */
   {946781610u, 2945u, a_AMV_VF_NONE},   /* smime-ca-file */
   {1507345877u, 2959u, a_AMV_VF_NONE},   /* smime-ca-flags */
   {2951976498u, 2974u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* smime-ca-no-defaults */
   {1752439545u, 2995u, a_AMV_VF_NONE|a_AMV_VF_CHAIN},   /* smime-cipher */
   {102302029u, 3008u, a_AMV_VF_NONE},   /* smime-crl-dir */
   {86428004u, 3022u, a_AMV_VF_NONE},   /* smime-crl-file */
   {237746033u, 3037u, a_AMV_VF_NONE|a_AMV_VF_CHAIN},   /* smime-encrypt */
   {2767628932u, 3051u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* smime-force-encryption */
   {1005584095u, 3074u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_OBSOLETE},   /* smime-no-default-ca */
   {2610149716u, 3094u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* smime-sign */
   {4112782207u, 3105u, a_AMV_VF_NONE|a_AMV_VF_CHAIN},   /* smime-sign-cert */
   {1704393517u, 3121u, a_AMV_VF_NONE|a_AMV_VF_CHAIN},   /* smime-sign-digest */
   {2740251050u, 3139u, a_AMV_VF_NONE|a_AMV_VF_CHAIN},   /* smime-sign-include-certs */
   {3761658326u, 3164u, a_AMV_VF_NONE|a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE},   /* smime-sign-message-digest */
   {1782732536u, 3190u, a_AMV_VF_NONE|a_AMV_VF_OBSOLETE},   /* smtp */
   {1658958037u, 3195u, a_AMV_VF_NONE|a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE},   /* smtp-auth */
   {3638650800u, 3205u, a_AMV_VF_NONE|a_AMV_VF_OBSOLETE},   /* smtp-auth-password */
   {2020555875u, 3224u, a_AMV_VF_NONE|a_AMV_VF_OBSOLETE},   /* smtp-auth-user */
   {2452298534u, 3239u, a_AMV_VF_NONE|a_AMV_VF_CHAIN},   /* smtp-config */
   {1076522903u, 3251u, a_AMV_VF_NONE|a_AMV_VF_VIP|a_AMV_VF_CHAIN},   /* smtp-from */
   {1820965540u, 3261u, a_AMV_VF_NONE|a_AMV_VF_VIP|a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE},   /* smtp-hostname */
   {1837607842u, 3275u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE},   /* smtp-use-starttls */
   {907387109u, 3293u, a_AMV_VF_NONE|a_AMV_VF_VIP|a_AMV_VF_IMPORT|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY},   /* SOCKS5_PROXY */
   {900761917u, 3306u, a_AMV_VF_NONE|a_AMV_VF_RDONLY|a_AMV_VF_IMPORT|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY|a_AMV_VF_POSNUM},   /* SOURCE_DATE_EPOCH */
   {3456900515u, 3324u, a_AMV_VF_NONE|a_AMV_VF_POSNUM},   /* socket-connect-timeout */
   {3775764645u, 3347u, a_AMV_VF_NONE|a_AMV_VF_VIP|a_AMV_VF_NOTEMPTY|a_AMV_VF_CHAIN},   /* socks-proxy */
   {1607330400u, 3359u, a_AMV_VF_NONE},   /* spam-interface */
   {1763068644u, 3374u, a_AMV_VF_NONE|a_AMV_VF_NOTEMPTY|a_AMV_VF_POSNUM},   /* spam-maxsize */
   {1908563950u, 3387u, a_AMV_VF_NONE},   /* spamc-command */
   {1452123120u, 3401u, a_AMV_VF_NONE},   /* spamc-arguments */
   {4013666858u, 3417u, a_AMV_VF_NONE},   /* spamc-user */
   {1923764058u, 3428u, a_AMV_VF_NONE},   /* spamfilter-ham */
   {3955925583u, 3443u, a_AMV_VF_NONE},   /* spamfilter-noham */
   {3561917382u, 3460u, a_AMV_VF_NONE},   /* spamfilter-nospam */
   {261790554u, 3478u, a_AMV_VF_NONE},   /* spamfilter-rate */
   {914178751u, 3494u, a_AMV_VF_NONE},   /* spamfilter-rate-scanscore */
   {2230056064u, 3520u, a_AMV_VF_NONE},   /* spamfilter-spam */
   {1769124455u, 3536u, a_AMV_VF_NONE|a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE},   /* ssl-ca-dir */
   {1778108319u, 3547u, a_AMV_VF_NONE|a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE},   /* ssl-ca-file */
   {3110362859u, 3559u, a_AMV_VF_NONE|a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE},   /* ssl-ca-flags */
   {623065149u, 3572u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE},   /* ssl-ca-no-defaults */
   {139775082u, 3591u, a_AMV_VF_NONE|a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE},   /* ssl-cert */
   {2317777583u, 3600u, a_AMV_VF_NONE|a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE},   /* ssl-cipher-list */
   {3936220190u, 3616u, a_AMV_VF_NONE|a_AMV_VF_OBSOLETE},   /* ssl-config-file */
   {315983966u, 3632u, a_AMV_VF_NONE|a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE},   /* ssl-config-module */
   {1105329479u, 3650u, a_AMV_VF_NONE|a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE},   /* ssl-config-pairs */
   {800287693u, 3667u, a_AMV_VF_NONE|a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE},   /* ssl-curves */
   {542424727u, 3678u, a_AMV_VF_NONE|a_AMV_VF_OBSOLETE},   /* ssl-crl-dir */
   {1605928646u, 3690u, a_AMV_VF_NONE|a_AMV_VF_OBSOLETE},   /* ssl-crl-file */
   {2392084957u, 3703u, a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL|a_AMV_VF_OBSOLETE},   /* ssl-features */
   {4242392148u, 3716u, a_AMV_VF_NONE|a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE},   /* ssl-key */
   {842733395u, 3724u, a_AMV_VF_NONE|a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE},   /* ssl-method */
   {120659094u, 3735u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_OBSOLETE},   /* ssl-no-default-ca */
   {3391235883u, 3753u, a_AMV_VF_NONE|a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE},   /* ssl-protocol */
   {2493237115u, 3766u, a_AMV_VF_NONE|a_AMV_VF_OBSOLETE},   /* ssl-rand-egd */
   {1150749481u, 3779u, a_AMV_VF_NONE|a_AMV_VF_OBSOLETE},   /* ssl-rand-file */
   {3001703062u, 3793u, a_AMV_VF_NONE|a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE},   /* ssl-verify */
   {3060393762u, 3804u, a_AMV_VF_NONE},   /* stealthmua */
   {3170554710u, 3815u, a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL},   /* system-mailrc */
   {1689227859u, 3829u, a_AMV_VF_NONE|a_AMV_VF_ENV},   /* TERM */
   {275160966u, 3834u, a_AMV_VF_NONE|a_AMV_VF_VIP|a_AMV_VF_DEFVAL|a_AMV_VF_IMPORT|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY},   /* TMPDIR */
   {2006033901u, 3841u, a_AMV_VF_NONE},   /* termcap */
   {1881431006u, 3849u, a_AMV_VF_NONE},   /* termcap-ca-mode */
   {3874156389u, 3865u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* termcap-disable */
   {49001407u, 3881u, a_AMV_VF_NONE|a_AMV_VF_CHAIN},   /* tls-ca-dir */
   {2310520195u, 3892u, a_AMV_VF_NONE|a_AMV_VF_CHAIN},   /* tls-ca-file */
   {1223767828u, 3904u, a_AMV_VF_NONE|a_AMV_VF_CHAIN},   /* tls-ca-flags */
   {3113270631u, 3917u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_CHAIN},   /* tls-ca-no-defaults */
   {172056861u, 3936u, a_AMV_VF_NONE},   /* tls-config-file */
   {3002246919u, 3952u, a_AMV_VF_NONE|a_AMV_VF_CHAIN},   /* tls-config-module */
   {789322284u, 3970u, a_AMV_VF_NONE|a_AMV_VF_CHAIN},   /* tls-config-pairs */
   {3248783469u, 3987u, a_AMV_VF_NONE},   /* tls-crl-dir */
   {1888319427u, 3999u, a_AMV_VF_NONE},   /* tls-crl-file */
   {4259586683u, 4012u, a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL},   /* tls-features */
   {1139189225u, 4025u, a_AMV_VF_NONE|a_AMV_VF_CHAIN},   /* tls-fingerprint */
   {2530971234u, 4041u, a_AMV_VF_NONE|a_AMV_VF_CHAIN},   /* tls-fingerprint-digest */
   {2971415438u, 4064u, a_AMV_VF_NONE},   /* tls-rand-file */
   {3259662180u, 4078u, a_AMV_VF_NONE|a_AMV_VF_CHAIN},   /* tls-verify */
   {3045770460u, 4089u, a_AMV_VF_NONE|a_AMV_VF_DEFVAL|a_AMV_VF_NOTEMPTY|a_AMV_VF_NUM},   /* toplines */
   {2347832344u, 4098u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* topsqueeze */
   {3335676089u, 4109u, a_AMV_VF_NONE|a_AMV_VF_VIP|a_AMV_VF_DEFVAL|a_AMV_VF_NOTEMPTY},   /* ttycharset */
   {807899482u, 4120u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_VIP},   /* typescript-mode */
   {330400956u, 4136u, a_AMV_VF_NONE|a_AMV_VF_RDONLY|a_AMV_VF_IMPORT|a_AMV_VF_ENV},   /* USER */
   {1567917856u, 4141u, a_AMV_VF_NONE|a_AMV_VF_VIP|a_AMV_VF_NODEL|a_AMV_VF_I3VAL|a_AMV_VF_POSNUM},   /* umask */
   {875435785u, 4147u, a_AMV_VF_NONE|a_AMV_VF_NOTEMPTY|a_AMV_VF_CHAIN},   /* user */
   {1942497279u, 4152u, a_AMV_VF_NONE|a_AMV_VF_DEFVAL|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY},   /* VISUAL */
   {691216848u, 4159u, a_AMV_VF_NONE|a_AMV_VF_I3VAL},   /* v15-compat */
   {3973338304u, 4170u, a_AMV_VF_NONE|a_AMV_VF_VIP|a_AMV_VF_POSNUM},   /* verbose */
   {944087093u, 4178u, a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL},   /* version */
   {1337487108u, 4186u, a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL},   /* version-date */
   {3081657388u, 4199u, a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL|a_AMV_VF_POSNUM},   /* version-hexnum */
   {1921844491u, 4214u, a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL|a_AMV_VF_POSNUM},   /* version-major */
   {1707804737u, 4228u, a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL|a_AMV_VF_POSNUM},   /* version-minor */
   {3760910668u, 4242u, a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL|a_AMV_VF_POSNUM},   /* version-update */
   {432301395u, 4257u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* writebackedited */
   {1643918527u, 4273u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_CHAIN},   /* disconnected */
   {259555527u, 4286u, a_AMV_VF_NONE|a_AMV_VF_CHAIN},   /* imap-auth */
   {3710399665u, 4296u, a_AMV_VF_NONE},   /* imap-cache */
   {3006849165u, 4307u, a_AMV_VF_NONE|a_AMV_VF_CHAIN},   /* imap-delim */
   {1681336106u, 4318u, a_AMV_VF_NONE|a_AMV_VF_CHAIN},   /* imap-keepalive */
   {3435503022u, 4333u, a_AMV_VF_NONE},   /* imap-list-depth */
   {2746817971u, 4349u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_CHAIN},   /* imap-use-starttls */
   {1557856483u, 4367u, a_AMV_VF_NONE|a_AMV_VF_ENV},   /* _S_MAILX_TEST */
};

#ifndef a__CREATE_OKEY_MAP_PL
# undef a_X
# ifdef mx_HAVE_PUTENV
#  define a_X(X) X
# else
#  define a_X(X)
# endif

CTAV(4 == FIELD_SIZEOF(struct a_amv_var_chain_map_bsrch, avcmb_prefix));
static struct a_amv_var_chain_map const a_amv_var_chain_map[] = {
   {4273u, ok_b_disconnected},
   {4286u, ok_v_imap_auth},
   {4307u, ok_v_imap_delim},
   {4318u, ok_v_imap_keepalive},
   {4349u, ok_b_imap_use_starttls},
   {2009u, ok_b_netrc_lookup},
   {2296u, ok_v_password},
   {2313u, ok_v_pop3_auth},
   {2353u, ok_b_pop3_no_apop},
   {2366u, ok_b_pop3_use_starttls},
   {2995u, ok_v_smime_cipher},
   {3037u, ok_v_smime_encrypt},
   {3105u, ok_v_smime_sign_cert},
   {3121u, ok_v_smime_sign_digest},
   {3139u, ok_v_smime_sign_include_certs},
   {3164u, ok_v_smime_sign_message_digest},
   {3195u, ok_v_smtp_auth},
   {3239u, ok_v_smtp_config},
   {3251u, ok_v_smtp_from},
   {3261u, ok_v_smtp_hostname},
   {3275u, ok_b_smtp_use_starttls},
   {3347u, ok_v_socks_proxy},
   {3536u, ok_v_ssl_ca_dir},
   {3547u, ok_v_ssl_ca_file},
   {3559u, ok_v_ssl_ca_flags},
   {3572u, ok_b_ssl_ca_no_defaults},
   {3591u, ok_v_ssl_cert},
   {3600u, ok_v_ssl_cipher_list},
   {3632u, ok_v_ssl_config_module},
   {3650u, ok_v_ssl_config_pairs},
   {3667u, ok_v_ssl_curves},
   {3716u, ok_v_ssl_key},
   {3724u, ok_v_ssl_method},
   {3753u, ok_v_ssl_protocol},
   {3793u, ok_v_ssl_verify},
   {3881u, ok_v_tls_ca_dir},
   {3892u, ok_v_tls_ca_file},
   {3904u, ok_v_tls_ca_flags},
   {3917u, ok_b_tls_ca_no_defaults},
   {3952u, ok_v_tls_config_module},
   {3970u, ok_v_tls_config_pairs},
   {4025u, ok_v_tls_fingerprint},
   {4041u, ok_v_tls_fingerprint_digest},
   {4078u, ok_v_tls_verify},
   {4147u, ok_v_user},
};
#define a_AMV_VAR_CHAIN_MAP_CNT 45

static struct a_amv_var_chain_map_bsrch const a_amv_var_chain_map_bsrch[] = {
   {"disc", 0u, ok_b_disconnected},
   {"imap", 1u, ok_b_imap_use_starttls},
   {"netr", 5u, ok_b_netrc_lookup},
   {"pass", 6u, ok_v_password},
   {"pop3", 7u, ok_b_pop3_use_starttls},
   {"smim", 10u, ok_v_smime_sign_message_digest},
   {"smtp", 16u, ok_b_smtp_use_starttls},
   {"sock", 21u, ok_v_socks_proxy},
   {"ssl-", 22u, ok_v_ssl_verify},
   {"tls-", 35u, ok_v_tls_verify},
   {"user", 44u, ok_v_user},
};
#define a_AMV_VAR_CHAIN_MAP_BSRCH_CNT 11

/* Unfortunately init of varsized buffer impossible: define "subclass"es */
static char const a_amv_var_virt_build_cc_val[] = {VAL_BUILD_CC_ARRAY};
static struct{
   struct a_amv_var *av_link;
   char const *av_value;
   a_X(char *av_env;)
   u32 av_flags;
   char const av_name[8 +1];
} const a_amv_var_virt_build_cc = {NIL, a_amv_var_virt_build_cc_val, a_X(0 su_COMMA) a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL, "build-cc"};

static char const a_amv_var_virt_build_ld_val[] = {VAL_BUILD_LD_ARRAY};
static struct{
   struct a_amv_var *av_link;
   char const *av_value;
   a_X(char *av_env;)
   u32 av_flags;
   char const av_name[8 +1];
} const a_amv_var_virt_build_ld = {NIL, a_amv_var_virt_build_ld_val, a_X(0 su_COMMA) a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL, "build-ld"};

static char const a_amv_var_virt_build_os_val[] = {VAL_BUILD_OS};
static struct{
   struct a_amv_var *av_link;
   char const *av_value;
   a_X(char *av_env;)
   u32 av_flags;
   char const av_name[8 +1];
} const a_amv_var_virt_build_os = {NIL, a_amv_var_virt_build_os_val, a_X(0 su_COMMA) a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL, "build-os"};

static char const a_amv_var_virt_build_rest_val[] = {VAL_BUILD_REST_ARRAY};
static struct{
   struct a_amv_var *av_link;
   char const *av_value;
   a_X(char *av_env;)
   u32 av_flags;
   char const av_name[10 +1];
} const a_amv_var_virt_build_rest = {NIL, a_amv_var_virt_build_rest_val, a_X(0 su_COMMA) a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL, "build-rest"};

static char const a_amv_var_virt_contact_mail_val[] = {VAL_CONTACT_MAIL};
static struct{
   struct a_amv_var *av_link;
   char const *av_value;
   a_X(char *av_env;)
   u32 av_flags;
   char const av_name[12 +1];
} const a_amv_var_virt_contact_mail = {NIL, a_amv_var_virt_contact_mail_val, a_X(0 su_COMMA) a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL, "contact-mail"};

static char const a_amv_var_virt_contact_web_val[] = {VAL_CONTACT_WEB};
static struct{
   struct a_amv_var *av_link;
   char const *av_value;
   a_X(char *av_env;)
   u32 av_flags;
   char const av_name[11 +1];
} const a_amv_var_virt_contact_web = {NIL, a_amv_var_virt_contact_web_val, a_X(0 su_COMMA) a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL, "contact-web"};

static char const a_amv_var_virt_features_val[] = {VAL_FEATURES};
static struct{
   struct a_amv_var *av_link;
   char const *av_value;
   a_X(char *av_env;)
   u32 av_flags;
   char const av_name[8 +1];
} const a_amv_var_virt_features = {NIL, a_amv_var_virt_features_val, a_X(0 su_COMMA) a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL, "features"};

static char const a_amv_var_virt_ssl_features_val[] = {VAL_TLS_FEATURES};
static struct{
   struct a_amv_var *av_link;
   char const *av_value;
   a_X(char *av_env;)
   u32 av_flags;
   char const av_name[12 +1];
} const a_amv_var_virt_ssl_features = {NIL, a_amv_var_virt_ssl_features_val, a_X(0 su_COMMA) a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL|a_AMV_VF_OBSOLETE, "ssl-features"};

static char const a_amv_var_virt_system_mailrc_val[] = {VAL_SYSCONFDIR "/" VAL_SYSCONFRC};
static struct{
   struct a_amv_var *av_link;
   char const *av_value;
   a_X(char *av_env;)
   u32 av_flags;
   char const av_name[13 +1];
} const a_amv_var_virt_system_mailrc = {NIL, a_amv_var_virt_system_mailrc_val, a_X(0 su_COMMA) a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL, "system-mailrc"};

static char const a_amv_var_virt_tls_features_val[] = {VAL_TLS_FEATURES};
static struct{
   struct a_amv_var *av_link;
   char const *av_value;
   a_X(char *av_env;)
   u32 av_flags;
   char const av_name[12 +1];
} const a_amv_var_virt_tls_features = {NIL, a_amv_var_virt_tls_features_val, a_X(0 su_COMMA) a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL, "tls-features"};

static char const a_amv_var_virt_version_val[] = {mx_VERSION};
static struct{
   struct a_amv_var *av_link;
   char const *av_value;
   a_X(char *av_env;)
   u32 av_flags;
   char const av_name[7 +1];
} const a_amv_var_virt_version = {NIL, a_amv_var_virt_version_val, a_X(0 su_COMMA) a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL, "version"};

static char const a_amv_var_virt_version_date_val[] = {mx_VERSION_DATE};
static struct{
   struct a_amv_var *av_link;
   char const *av_value;
   a_X(char *av_env;)
   u32 av_flags;
   char const av_name[12 +1];
} const a_amv_var_virt_version_date = {NIL, a_amv_var_virt_version_date_val, a_X(0 su_COMMA) a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL, "version-date"};

static char const a_amv_var_virt_version_hexnum_val[] = {mx_VERSION_HEXNUM};
static struct{
   struct a_amv_var *av_link;
   char const *av_value;
   a_X(char *av_env;)
   u32 av_flags;
   char const av_name[14 +1];
} const a_amv_var_virt_version_hexnum = {NIL, a_amv_var_virt_version_hexnum_val, a_X(0 su_COMMA) a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL|a_AMV_VF_POSNUM, "version-hexnum"};

static char const a_amv_var_virt_version_major_val[] = {mx_VERSION_MAJOR};
static struct{
   struct a_amv_var *av_link;
   char const *av_value;
   a_X(char *av_env;)
   u32 av_flags;
   char const av_name[13 +1];
} const a_amv_var_virt_version_major = {NIL, a_amv_var_virt_version_major_val, a_X(0 su_COMMA) a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL|a_AMV_VF_POSNUM, "version-major"};

static char const a_amv_var_virt_version_minor_val[] = {mx_VERSION_MINOR};
static struct{
   struct a_amv_var *av_link;
   char const *av_value;
   a_X(char *av_env;)
   u32 av_flags;
   char const av_name[13 +1];
} const a_amv_var_virt_version_minor = {NIL, a_amv_var_virt_version_minor_val, a_X(0 su_COMMA) a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL|a_AMV_VF_POSNUM, "version-minor"};

static char const a_amv_var_virt_version_update_val[] = {mx_VERSION_UPDATE};
static struct{
   struct a_amv_var *av_link;
   char const *av_value;
   a_X(char *av_env;)
   u32 av_flags;
   char const av_name[14 +1];
} const a_amv_var_virt_version_update = {NIL, a_amv_var_virt_version_update_val, a_X(0 su_COMMA) a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL|a_AMV_VF_POSNUM, "version-update"};

static struct a_amv_var_virt const a_amv_var_virts[] = {
   {ok_v_build_cc, {0,}, (void const*)&a_amv_var_virt_build_cc},
   {ok_v_build_ld, {0,}, (void const*)&a_amv_var_virt_build_ld},
   {ok_v_build_os, {0,}, (void const*)&a_amv_var_virt_build_os},
   {ok_v_build_rest, {0,}, (void const*)&a_amv_var_virt_build_rest},
   {ok_v_contact_mail, {0,}, (void const*)&a_amv_var_virt_contact_mail},
   {ok_v_contact_web, {0,}, (void const*)&a_amv_var_virt_contact_web},
   {ok_v_features, {0,}, (void const*)&a_amv_var_virt_features},
   {ok_v_ssl_features, {0,}, (void const*)&a_amv_var_virt_ssl_features},
   {ok_v_system_mailrc, {0,}, (void const*)&a_amv_var_virt_system_mailrc},
   {ok_v_tls_features, {0,}, (void const*)&a_amv_var_virt_tls_features},
   {ok_v_version, {0,}, (void const*)&a_amv_var_virt_version},
   {ok_v_version_date, {0,}, (void const*)&a_amv_var_virt_version_date},
   {ok_v_version_hexnum, {0,}, (void const*)&a_amv_var_virt_version_hexnum},
   {ok_v_version_major, {0,}, (void const*)&a_amv_var_virt_version_major},
   {ok_v_version_minor, {0,}, (void const*)&a_amv_var_virt_version_minor},
   {ok_v_version_update, {0,}, (void const*)&a_amv_var_virt_version_update},
};
#define a_AMV_VAR_VIRTS_CNT 16

static struct a_amv_var_defval const a_amv_var_i3vals[] = {
   {ok_b_asksub, {0,}, NIL},
   {ok_v_datefield, {0,}, "%Y-%m-%d %H:%M"},
   {ok_v_datefield_markout_older, {0,}, "%Y-%m-%d"},
   {ok_b_header, {0,}, NIL},
   {ok_v_ifs_ws, {0,}, " \t\n"},
   {ok_v_log_prefix, {0,}, VAL_UAGENT ": "},
   {ok_b_mbox_fcc_and_pcc, {0,}, NIL},
   {ok_v_prompt, {0,}, "? "},
   {ok_v_prompt2, {0,}, ".. "},
   {ok_b_save, {0,}, NIL},
   {ok_v_sendwait, {0,}, ""},
   {ok_v_umask, {0,}, "0077"},
   {ok_v_v15_compat, {0,}, "y"},
};
#define a_AMV_VAR_I3VALS_CNT 13

static struct a_amv_var_defval const a_amv_var_defvals[] = {
   {ok_v_bind_inter_byte_timeout, {0,}, mx_BIND_INTER_BYTE_TIMEOUT},
   {ok_v_charset_7bit, {0,}, CHARSET_7BIT},
   {ok_v_charset_8bit, {0,}, CHARSET_8BIT},
   {ok_v_content_description_forwarded_message, {0,}, mx_CONTENT_DESC_FORWARDED_MESSAGE},
   {ok_v_content_description_quote_attachment, {0,}, mx_CONTENT_DESC_QUOTE_ATTACHMENT},
   {ok_v_content_description_smime_message, {0,}, mx_CONTENT_DESC_SMIME_MESSAGE},
   {ok_v_content_description_smime_signature, {0,}, mx_CONTENT_DESC_SMIME_SIG},
   {ok_v_DEAD, {0,}, VAL_DEAD},
   {ok_v_EDITOR, {0,}, VAL_EDITOR},
   {ok_v_errors_limit, {0,}, VAL_ERRORS_LIMIT},
   {ok_v_escape, {0,}, n_ESCAPE},
   {ok_v_ifs, {0,}, " \t\n"},
   {ok_v_indentprefix, {0,}, "\t"},
   {ok_v_line_editor_cpl_word_breaks, {0,}, n_LINE_EDITOR_CPL_WORD_BREAKS},
   {ok_v_LISTER, {0,}, VAL_LISTER},
   {ok_v_MAILCAPS, {0,}, VAL_MAILCAPS},
   {ok_v_MAILRC, {0,}, VAL_MAILRC},
   {ok_v_MBOX, {0,}, VAL_MBOX},
   {ok_v_mta, {0,}, VAL_MTA},
   {ok_v_mta_argv0, {0,}, VAL_MTA_ARGV0},
   {ok_v_NETRC, {0,}, VAL_NETRC},
   {ok_v_PAGER, {0,}, VAL_PAGER},
   {ok_v_quote_chars, {0,}, ">|}:"},
   {ok_v_SHELL, {0,}, VAL_SHELL},
   {ok_v_TMPDIR, {0,}, VAL_TMPDIR},
   {ok_v_toplines, {0,}, "5"},
   {ok_v_ttycharset, {0,}, CHARSET_8BIT},
   {ok_v_VISUAL, {0,}, VAL_VISUAL},
};
#define a_AMV_VAR_DEFVALS_CNT 28

#define a_AMV_VAR__SPECIAL_PARAM_MAP_IDX 0u
#define a_AMV_VAR__QM_MAP_IDX 1u
#define a_AMV_VAR__EM_MAP_IDX 2u

# undef a_X
#endif /* !a__CREATE_OKEY_MAP_PL */
#define a_AMV_VAR_REV_ILL 331u
#define a_AMV_VAR_REV_PRIME 619u
#define a_AMV_VAR_REV_LONGEST 6u
#define a_AMV_VAR_REV_WRAPAROUND 0
static u16 const a_amv_var_revmap[a_AMV_VAR_REV_PRIME] = {
  216u, 163u, 331u, 331u, 171u, 331u, 248u, 283u, 307u, 331u,
  2u, 23u, 256u, 331u, 331u, 142u, 331u, 119u, 122u, 331u,
  24u, 331u, 331u, 331u, 331u, 47u, 236u, 304u, 331u, 331u,
  331u, 28u, 215u, 152u, 331u, 121u, 183u, 145u, 237u, 255u,
  331u, 331u, 179u, 207u, 71u, 246u, 291u, 331u, 331u, 331u,
  218u, 331u, 331u, 56u, 64u, 316u, 331u, 331u, 331u, 331u,
  149u, 331u, 53u, 331u, 228u, 331u, 331u, 331u, 331u, 331u,
  331u, 331u, 85u, 6u, 331u, 331u, 331u, 331u, 39u, 79u,
  137u, 112u, 235u, 301u, 331u, 331u, 331u, 331u, 113u, 331u,
  157u, 331u, 331u, 331u, 331u, 331u, 158u, 331u, 42u, 167u,
  331u, 72u, 298u, 331u, 331u, 331u, 12u, 105u, 331u, 331u,
  331u, 261u, 331u, 331u, 331u, 331u, 331u, 331u, 331u, 331u,
  73u, 144u, 331u, 238u, 331u, 92u, 331u, 331u, 331u, 233u,
  278u, 292u, 331u, 103u, 31u, 204u, 305u, 331u, 65u, 54u,
  331u, 20u, 147u, 186u, 311u, 331u, 331u, 98u, 331u, 306u,
  209u, 331u, 68u, 331u, 331u, 331u, 4u, 153u, 242u, 331u,
  331u, 324u, 230u, 156u, 331u, 111u, 331u, 331u, 331u, 331u,
  331u, 200u, 265u, 270u, 331u, 70u, 181u, 268u, 184u, 279u,
  126u, 312u, 331u, 90u, 331u, 331u, 191u, 331u, 140u, 286u,
  83u, 22u, 317u, 331u, 331u, 223u, 141u, 247u, 16u, 285u,
  302u, 331u, 331u, 161u, 331u, 162u, 253u, 315u, 331u, 159u,
  82u, 212u, 331u, 331u, 125u, 169u, 189u, 331u, 94u, 331u,
  331u, 331u, 331u, 166u, 308u, 331u, 131u, 295u, 331u, 331u,
  331u, 331u, 331u, 174u, 211u, 331u, 224u, 7u, 331u, 45u,
  138u, 148u, 118u, 198u, 264u, 296u, 80u, 331u, 77u, 331u,
  11u, 185u, 173u, 89u, 331u, 35u, 108u, 136u, 201u, 327u,
  38u, 331u, 331u, 15u, 331u, 331u, 331u, 331u, 195u, 101u,
  331u, 151u, 331u, 331u, 331u, 214u, 210u, 331u, 241u, 5u,
  76u, 243u, 135u, 331u, 331u, 84u, 331u, 227u, 226u, 331u,
  331u, 331u, 258u, 331u, 331u, 331u, 81u, 331u, 331u, 331u,
  331u, 331u, 331u, 331u, 44u, 75u, 331u, 331u, 133u, 252u,
  331u, 193u, 277u, 9u, 290u, 331u, 331u, 331u, 331u, 331u,
  58u, 303u, 331u, 331u, 331u, 91u, 213u, 187u, 331u, 331u,
  331u, 331u, 331u, 331u, 190u, 116u, 134u, 88u, 254u, 165u,
  109u, 74u, 326u, 331u, 331u, 331u, 331u, 299u, 19u, 331u,
  69u, 86u, 155u, 3u, 331u, 297u, 182u, 331u, 331u, 331u,
  331u, 331u, 41u, 115u, 36u, 331u, 25u, 289u, 273u, 331u,
  331u, 146u, 192u, 170u, 29u, 321u, 331u, 331u, 139u, 123u,
  313u, 17u, 287u, 331u, 331u, 331u, 331u, 331u, 325u, 331u,
  52u, 130u, 8u, 124u, 331u, 331u, 331u, 331u, 331u, 331u,
  331u, 59u, 331u, 175u, 180u, 331u, 231u, 55u, 194u, 229u,
  114u, 197u, 205u, 328u, 331u, 331u, 331u, 331u, 331u, 168u,
  331u, 310u, 0u, 331u, 331u, 331u, 178u, 331u, 271u, 331u,
  61u, 331u, 129u, 244u, 281u, 331u, 331u, 331u, 331u, 331u,
  331u, 106u, 282u, 331u, 331u, 331u, 87u, 331u, 331u, 208u,
  222u, 30u, 320u, 331u, 331u, 331u, 99u, 33u, 331u, 331u,
  331u, 322u, 107u, 331u, 46u, 172u, 331u, 331u, 331u, 102u,
  199u, 331u, 331u, 331u, 331u, 331u, 331u, 331u, 331u, 331u,
  331u, 127u, 331u, 331u, 10u, 21u, 48u, 331u, 160u, 60u,
  117u, 266u, 188u, 249u, 309u, 294u, 331u, 32u, 120u, 128u,
  257u, 331u, 331u, 50u, 143u, 43u, 51u, 57u, 300u, 331u,
  331u, 219u, 331u, 225u, 234u, 331u, 331u, 267u, 232u, 18u,
  93u, 150u, 280u, 329u, 331u, 67u, 100u, 319u, 37u, 331u,
  331u, 331u, 331u, 331u, 331u, 331u, 331u, 331u, 164u, 239u,
  331u, 331u, 331u, 331u, 203u, 251u, 274u, 331u, 97u, 269u,
  331u, 331u, 206u, 318u, 263u, 196u, 221u, 331u, 154u, 331u,
  272u, 14u, 78u, 49u, 104u, 34u, 293u, 331u, 331u, 240u,
  27u, 63u, 331u, 331u, 202u, 217u, 110u, 259u, 260u, 331u,
  250u, 177u, 331u, 331u, 331u, 331u, 331u, 331u, 331u, 331u,
  331u, 331u, 66u, 331u, 314u, 331u, 331u, 331u, 262u, 275u,
  1u, 95u, 245u, 284u, 331u, 220u, 13u, 331u, 26u, 331u,
  288u, 323u, 62u, 96u, 330u, 132u, 176u, 276u, 40u
};
